import fs from'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const write=(p,s)=>fs.writeFileSync(p,s);
function mustReplace(text,oldText,newText,label){if(!text.includes(oldText))throw new Error(`Missing patch target: ${label}`);return text.replace(oldText,newText)}

let state=read('legal-app/js/state.js');
state=mustReplace(state,"export function save(){localStorage.setItem(KEY,JSON.stringify(state))}",`function emitStateSaved(){if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('lexifrance:state-saved',{detail:{at:now()}}))}\nexport function save(emit=true){localStorage.setItem(KEY,JSON.stringify(state));if(emit)emitStateSaved()}\nexport function stateSnapshot(){return clone(state)}\nexport function replaceState(next,{emit=true}={}){for(const k of Object.keys(state))delete state[k];Object.assign(state,{...base(),...clone(next||{})});localStorage.setItem(KEY,JSON.stringify(state));applyPrefs();if(emit)emitStateSaved();return state}`, 'state cloud bridge');
write('legal-app/js/state.js',state);

let app=read('legal-app/app.js');
app=mustReplace(app,"import{migrateCourseV5,migrateSolveV2}from'./js/state.js';","import{migrateCourseV5,migrateSolveV2}from'./js/state.js';\nimport{initCloud}from'./js/cloud.js?v=11';",'cloud import');
app=app.replaceAll("./js/pages.js?v=10","./js/pages.js?v=11").replaceAll("./js/lesson.js?v=10","./js/lesson.js?v=11").replaceAll("./js/case.js?v=10","./js/case.js?v=11").replaceAll("./js/legal-enhance.js?v=10","./js/legal-enhance.js?v=11");
app=mustReplace(app,"try{await boot();migrateCourseV5(idx().legacyLessonMap||{});migrateSolveV2();await render()}catch(e)","try{await boot();migrateCourseV5(idx().legacyLessonMap||{});migrateSolveV2();await render();initCloud({contentRelease:idx().contentRelease,onHydrate:()=>render()}).catch(e=>console.warn('LexiFrance cloud unavailable',e))}catch(e)",'nonblocking cloud init');
write('legal-app/app.js',app);

let pages=read('legal-app/js/pages.js');
pages=mustReplace(pages,"import{section,levelCard,masteryBar,pathCard,errorBox,statusBadge}from'./ui.js';import{pathIcon,icon}from'./icons.js';","import{section,levelCard,masteryBar,pathCard,errorBox,statusBadge}from'./ui.js';import{pathIcon,icon}from'./icons.js';\nimport{getCloudStatus,queueStateForSync,requestAccountUpgrade}from'./cloud.js?v=11';",'pages cloud import');
const cloudHelper=`\nfunction cloudPanel(){const c=getCloudStatus(),label=c.mode==='account'?'Аккаунт':c.mode==='anonymous'?'Облачный гость':'Локально',detail=c.mode==='account'?(c.email||'Аккаунт подключен'):c.mode==='anonymous'?'Прогресс привязан к анонимному cloud ID. Добавьте email, чтобы не потерять доступ на другом устройстве.':c.status==='local_only'?'Supabase Auth пока недоступен. Локальный прогресс продолжает работать.':'LexiFrance продолжает работать локально и подключит cloud при доступной сети.',sync=c.status==='synced'?'Синхронизировано':c.status==='syncing'?'Синхронизация...':c.status==='offline'?'Offline':c.pending?`В очереди: ${c.pending}`:'Cloud готов';return `<section class="section cloud-account">${section('00','Облачный прогресс',sync)}<div class="card legal-card"><div class="tag">${label}</div><h3>${detail}</h3><p class="small">${c.lastSyncAt?`Последняя синхронизация: ${new Date(c.lastSyncAt).toLocaleString('ru-RU')}`:'Локальный режим всегда остается доступен.'}</p><button class="secondary" data-cloud-sync>Синхронизировать сейчас</button>${c.mode!=='account'?`<div style="margin-top:14px"><label class="small" for="cloudEmail">Сохранить прогресс в постоянном аккаунте</label><div class="search-box" style="margin-top:6px"><input id="cloudEmail" type="email" inputmode="email" autocomplete="email" placeholder="email@example.com"></div><button class="primary" data-cloud-upgrade style="margin-top:8px">Привязать email</button><div class="small" data-cloud-message style="margin-top:6px"></div></div>`:''}</div></section>`}\n`;
pages=mustReplace(pages,"export async function profile(){",cloudHelper+"export async function profile(){",'cloud profile helper');
pages=mustReplace(pages,"<div class=\"card profile-grid\"><div class=\"stat\"><b>${state.xp}</b><span>XP</span></div><div class=\"stat\"><b>${state.streak}</b><span>серия дней</span></div><div class=\"stat\"><b>${state.completed.length}</b><span>освоено уроков</span></div></div><section class=\"section\">","<div class=\"card profile-grid\"><div class=\"stat\"><b>${state.xp}</b><span>XP</span></div><div class=\"stat\"><b>${state.streak}</b><span>серия дней</span></div><div class=\"stat\"><b>${state.completed.length}</b><span>освоено уроков</span></div></div>${cloudPanel()}<section class=\"section\">",'profile cloud panel');
pages=mustReplace(pages,"export function bindProfile(root,ctx){root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));root.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>setFont(Number(b.dataset.font)));root.querySelectorAll('[data-saved-lesson]').forEach(b=>b.onclick=()=>ctx.openLesson(b.dataset.savedLesson))}",`export function bindProfile(root,ctx){root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));root.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>setFont(Number(b.dataset.font)));root.querySelectorAll('[data-saved-lesson]').forEach(b=>b.onclick=()=>ctx.openLesson(b.dataset.savedLesson));const sync=root.querySelector('[data-cloud-sync]');if(sync)sync.onclick=async()=>{sync.disabled=true;sync.textContent='Синхронизация...';try{await queueStateForSync('manual_profile');sync.textContent='Синхронизировано'}catch{sync.textContent='Сохранено локально'}finally{setTimeout(()=>{sync.disabled=false},800)}};const up=root.querySelector('[data-cloud-upgrade]'),email=root.querySelector('#cloudEmail'),msg=root.querySelector('[data-cloud-message]');if(up&&email)up.onclick=async()=>{up.disabled=true;if(msg)msg.textContent='Отправляем подтверждение...';try{await requestAccountUpgrade(email.value);if(msg)msg.textContent='Проверьте email и подтвердите адрес. Текущий прогресс сохранится.'}catch(e){if(msg)msg.textContent=e?.message||'Не удалось отправить письмо. Локальный прогресс сохранен.'}finally{up.disabled=false}}}`, 'profile cloud bindings');
write('legal-app/js/pages.js',pages);

let sw=read('legal-app/service-worker.js').replaceAll("v10","v11").replaceAll("?v=10","?v=11");
sw=mustReplace(sw,"'./js/data.js','./js/state.js'","'./js/data.js','./js/state.js','./js/cloud.js?v=11'",'cloud service worker shell');
write('legal-app/service-worker.js',sw);

let index=read('legal-app/index.html').replaceAll('?v=10','?v=11');write('legal-app/index.html',index);
let appIndex=read('legal-app/content/app-index.json');appIndex=mustReplace(appIndex,'"runtimeVersion":"10"','"runtimeVersion":"11"','runtime version');write('legal-app/content/app-index.json',appIndex);

const qa=`import fs from'node:fs';\nconst cloud=fs.readFileSync('legal-app/js/cloud.js','utf8');\nconst state=fs.readFileSync('legal-app/js/state.js','utf8');\nconst app=fs.readFileSync('legal-app/app.js','utf8');\nconst sw=fs.readFileSync('legal-app/service-worker.js','utf8');\nconst idx=JSON.parse(fs.readFileSync('legal-app/content/app-index.json','utf8'));\nconst fail=m=>{console.error('FAIL:',m);process.exitCode=1},pass=m=>console.log('PASS:',m),check=(v,m)=>v?pass(m):fail(m);\ncheck(cloud.includes('sb_publishable_'),'frontend uses publishable Supabase key');\ncheck(!/service[_-]?role/i.test(cloud),'frontend contains no service-role credential');\nfor(const k of ['eventId','entityType','entityId','operation','payload','createdAt','syncStatus'])check(cloud.includes(k),\`sync queue includes \\${k}\`);\ncheck(cloud.includes("status==='conflict'")&&cloud.includes('mergeProgress'),'CAS conflicts are explicitly merged');\ncheck(cloud.includes("signInAnonymously"),'soft anonymous auth is implemented');\ncheck(cloud.includes('updateUser({email:value}'),'anonymous to email upgrade is implemented');\ncheck(state.includes("lexifrance:state-saved")&&state.includes('replaceState'),'existing state engine emits cloud changes without duplicate business rules');\ncheck(app.includes('initCloud')&&app.indexOf('await render();initCloud')>0,'cloud initialization happens after local render');\ncheck(sw.includes("VERSION='v11'")&&sw.includes('./js/cloud.js?v=11'),'PWA v11 precaches local cloud adapter');\ncheck(idx.runtimeVersion==='11','app index runtimeVersion is 11');\n`;
write('legal-app/qa-cloud.mjs',qa);

let workflow=read('.github/workflows/lexifrance-qa.yml');
workflow=workflow.replace("      - lexifrance-v5-solve2\n","      - lexifrance-v5-solve2\n      - lexifrance-next-phase1\n");
workflow=workflow.replace("      - name: Core integrity\n        run: node legal-app/qa.mjs\n","      - name: Core integrity\n        run: node legal-app/qa.mjs\n      - name: Phase 1 cloud integrity\n        run: node legal-app/qa-cloud.mjs\n");
write('.github/workflows/lexifrance-qa.yml',workflow);
console.log('Phase 1 frontend patch applied');
