const VERSION='v8';
const STATIC=`lexifrance-${VERSION}-static`;
const RUNTIME=`lexifrance-${VERSION}-runtime`;
const LEGAL=`lexifrance-${VERSION}-legal`;
const STATIC_ASSETS=['./icon.svg'];
const RUNTIME_ASSETS=['./','./index.html','./manifest.webmanifest','./app.css?v=8','./quiz.css?v=8','./app.js?v=8','./js/icons.js','./js/state.js','./js/data.js','./js/ui.js','./js/pages.js?v=8','./js/lesson.js?v=8','./js/case.js?v=8','./js/legal-enhance.js?v=8'];
const LESSON_IDS=['corp-01','corp-02','corp-03','corp-04','corp-05','tax-01','tax-02','tax-03','tax-04','imm-01','imm-02','imm-03','imm-04','imm-05','imm-06','re-01','re-02','re-03','re-04','re-05'];
const CASE_IDS=['case1','case2','case3','case4','case5','case6','case7','case8','case9','case10','case11'];
const LEGAL_BOOT=['./content/app-index.json','./content/updates.json','./content/catalog/corporate.json','./content/catalog/tax.json','./content/catalog/immigration.json','./content/catalog/real-estate.json','./content/search/core.json','./content/cases/index-1.json',...CASE_IDS.map(id=>`./content/cases/${id}.json`),...LESSON_IDS.map(id=>`./content/lessons/${id}.json`),...LESSON_IDS.map(id=>`./content/quizzes/${id}.json`)];
self.addEventListener('install',event=>event.waitUntil(Promise.all([caches.open(STATIC).then(c=>c.addAll(STATIC_ASSETS)),caches.open(RUNTIME).then(c=>c.addAll(RUNTIME_ASSETS)),caches.open(LEGAL).then(c=>c.addAll(LEGAL_BOOT))]).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('lexifrance-')&&![STATIC,RUNTIME,LEGAL].includes(k)).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function networkFirst(req,cacheName,fallback){const cache=await caches.open(cacheName);try{const res=await fetch(req,{cache:'no-store'});if(res.ok)await cache.put(req,res.clone());return res}catch(err){const hit=await cache.match(req,{ignoreSearch:false});if(hit)return hit;if(fallback){const f=await cache.match(fallback);if(f)return f}throw err}}
async function cacheFirst(req,cacheName){const cache=await caches.open(cacheName),hit=await cache.match(req,{ignoreSearch:false});if(hit)return hit;const res=await fetch(req);if(res.ok)await cache.put(req,res.clone());return res}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;if(req.mode==='navigate'){event.respondWith(networkFirst(req,RUNTIME,'./index.html'));return}if(url.pathname.includes('/legal-app/content/')){event.respondWith(networkFirst(req,LEGAL));return}if(/\.(?:js|css)$/.test(url.pathname)||url.pathname.endsWith('/manifest.webmanifest')){event.respondWith(networkFirst(req,RUNTIME));return}if(/\.(?:svg|png|jpg|jpeg|webp|ico)$/.test(url.pathname)){event.respondWith(cacheFirst(req,STATIC));return}event.respondWith(networkFirst(req,RUNTIME).catch(()=>new Response('',{status:503})))});