const VERSION='v10';
const STATIC=`lexifrance-static-${VERSION}`;
const RUNTIME=`lexifrance-runtime-${VERSION}`;
const LEGAL=`lexifrance-legal-${VERSION}`;
const SHELL=['./','./index.html','./app.css?v=10','./quiz.css?v=10','./solve2.css?v=10','./app.js?v=10','./manifest.webmanifest','./js/data.js','./js/state.js','./js/search-core.js','./js/ui.js','./js/icons.js','./js/pages.js?v=10','./js/lesson.js?v=10','./js/case.js?v=10','./js/legal-enhance.js?v=10'];
const STATIC_ASSETS=['./icon.svg'];
const LESSONS=['corp-01','corp-02','corp-03','corp-04','corp-05','tax-01','tax-02','tax-03','tax-04','imm-01','imm-02','imm-03','imm-04','imm-05','imm-06','re-01','re-02','re-03','re-04','re-05'];
const CASE_BUNDLES=['corporate-v2','tax-v2','immigration-v2','real-estate-v2'];
const LEGAL_BOOT=['./content/app-index.json','./content/updates.json','./content/catalog/corporate.json','./content/catalog/tax.json','./content/catalog/immigration.json','./content/catalog/real-estate.json','./content/search/core.json','./content/search/qa.json','./content/cases/index-v2.json',...CASE_BUNDLES.map(id=>`./content/cases/${id}.json`),...LESSONS.map(id=>`./content/lessons/${id}.json`),...LESSONS.map(id=>`./content/quizzes/${id}.json`)];
async function bestEffortLegal(){const cache=await caches.open(LEGAL);await Promise.allSettled(LEGAL_BOOT.map(async url=>{const r=await fetch(url,{cache:'no-store'});if(r.ok)await cache.put(url,r.clone());else throw new Error(`LEGAL ${url} ${r.status}`)}))}
self.addEventListener('install',e=>e.waitUntil((async()=>{const runtime=await caches.open(RUNTIME);await runtime.addAll(SHELL);const statics=await caches.open(STATIC);await statics.addAll(STATIC_ASSETS);await bestEffortLegal();await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('lexifrance-')&&!([STATIC,RUNTIME,LEGAL].includes(k))).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function networkFirst(req,cacheName){const cache=await caches.open(cacheName);try{const r=await fetch(req,{cache:'no-store'});if(r&&r.ok){await cache.put(req,r.clone());return r}const hit=await cache.match(req);if(hit)return hit;if(r)return r;throw new Error('invalid-network-response')}catch(err){const hit=await cache.match(req);if(hit)return hit;throw err}}
async function cacheFirst(req){const cache=await caches.open(STATIC);const hit=await cache.match(req);if(hit)return hit;const r=await fetch(req);if(r&&r.ok)await cache.put(req,r.clone());return r}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);if(url.origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(networkFirst(e.request,RUNTIME).catch(()=>caches.match('./index.html')));return}if(url.pathname.includes('/legal-app/content/')){e.respondWith(networkFirst(e.request,LEGAL));return}if(/\.(?:js|css)$/.test(url.pathname)){e.respondWith(networkFirst(e.request,RUNTIME));return}if(/\.(?:svg|png|jpg|jpeg|webp|ico)$/.test(url.pathname)){e.respondWith(cacheFirst(e.request));return}e.respondWith(networkFirst(e.request,RUNTIME))});