import { oneCase, relatedLessons, usableStatus } from './data.js';
import {
  caseV2Progress,
  viewCase,
  activeCaseRun,
  ensureCaseRun,
  restartCaseRun,
  setCaseStage,
  saveCaseNotebook,
  saveCaseDraft,
  caseStageState,
  submitCaseStage,
  finishCaseV2
} from './state.js';
import { modalBase, statusBadge } from './ui.js';

function esc(value) {
  return String(value == null ? '' : value).replace(/[&<>"']/g, function (char) {
    var map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
    return map[char];
  });
}
function scoreLabel(score) { if (score >= 90) return 'Отличное решение'; if (score >= 75) return 'Хорошее решение'; if (score >= 60) return 'Рабочая стратегия'; if (score >= 40) return 'Есть существенные пробелы'; return 'Нужно вернуться к основам'; }
function list(value) { return Array.isArray(value) ? value : []; }
function dossierHTML(caseData) {
  var dossier = caseData.dossier || {}, client = caseData.client || {};
  var clientRows = Object.keys(client).filter(function (key) { return key !== 'name'; }).map(function (key) { return '<div><span>' + esc(key) + '</span><b>' + esc(client[key]) + '</b></div>'; }).join('');
  var facts = list(dossier.facts).map(function (fact) { return '<div class="fact-row"><span>' + esc(fact.label) + '</span><b>' + esc(fact.value) + '</b></div>'; }).join('');
  var timeline = list(dossier.timeline).map(function (row) { return '<div><b>' + esc(row.date) + '</b><span>' + esc(row.event) + '</span></div>'; }).join('');
  var docs = list(dossier.availableDocuments).map(function (doc) { return '<span>' + esc(doc) + '</span>'; }).join('');
  return '<section class="case-dossier"><div class="case-client card"><div class="tag">DOSSIER · ' + esc(caseData.level) + '</div><h2>' + esc(client.name || 'Клиент') + '</h2><div class="dossier-grid">' + clientRows + '</div></div><div class="card legal-card"><h3>Ситуация</h3><p>' + esc(dossier.summary || caseData.prompt || '') + '</p></div>' + (facts ? '<div class="card legal-card"><h3>Факты dossier</h3><div class="fact-list">' + facts + '</div></div>' : '') + (timeline ? '<div class="card legal-card"><h3>Timeline</h3><div class="timeline-list">' + timeline + '</div></div>' : '') + (docs ? '<div class="card legal-card"><h3>Уже есть в dossier</h3><div class="doc-chips">' + docs + '</div></div>' : '') + '</section>';
}
function notebookHTML(run) { var note = run && run.notebook ? run.notebook : ''; return '<section class="case-notebook card"><div class="tag">Ваш анализ</div><h3>Case Notebook</h3><p>Запишите проблему, аргументы или предварительную стратегию. LexiFrance не ставит AI-оценку этому тексту.</p><textarea id="caseNotebook" placeholder="Мой анализ...">' + esc(note) + '</textarea><div class="micro">Сохраняется локально на устройстве.</div></section>'; }
function progressHTML(caseData, run, index) { var tasks = list(caseData.tasks), pct = tasks.length ? index / tasks.length * 100 : 0, runText = run ? 'Run ' + caseV2Progress(caseData.id).attempts : 'Attempt еще не начат'; return '<div class="case-stage-progress card"><div><b>Этап ' + Math.min(index + 1, tasks.length) + ' из ' + tasks.length + '</b><span>' + runText + '</span></div><div class="progress"><i style="width:' + pct + '%"></i></div></div>'; }
function selectedFeedback(task, answer) {
  if (!Array.isArray(task.options)) return '';
  if (task.kind === 'multi') { var selected = new Set(Array.isArray(answer) ? answer : []); return task.options.filter(function (option) { return selected.has(option.id); }).map(function (option) { return '<div class="stage-feedback-line ' + (option.correct ? 'good' : 'bad') + '"><b>' + esc(option.text) + '</b><span>' + esc(option.feedback) + '</span></div>'; }).join(''); }
  var chosen = task.options.find(function (option) { return option.id === answer; });
  return chosen ? '<div class="stage-feedback-line ' + (chosen.correct ? 'good' : 'bad') + '"><b>' + esc(chosen.text) + '</b><span>' + esc(chosen.feedback) + '</span></div>' : '';
}
function stageRatio(task, answer) {
  if (task.kind === 'single') { var chosen = list(task.options).find(function (option) { return option.id === answer; }); return chosen && chosen.correct ? 1 : 0; }
  if (task.kind === 'multi') { var selected = new Set(Array.isArray(answer) ? answer : []), correct = list(task.options).filter(function (option) { return option.correct; }), tp = correct.filter(function (option) { return selected.has(option.id); }).length, precision = selected.size ? tp / selected.size : 0, recall = correct.length ? tp / correct.length : 0; return precision + recall ? 2 * precision * recall / (precision + recall) : 0; }
  if (task.kind === 'order') { var order = Array.isArray(answer) ? answer : [], correctOrder = list(task.correctOrder); if (!correctOrder.length) return 0; var positions = 0; correctOrder.forEach(function (id, index) { if (order[index] === id) positions += 1; }); return positions / correctOrder.length; }
  if (task.kind === 'number') { var value = Number(String(answer).replace(',', '.')); if (!Number.isFinite(value)) return 0; var expected = Number(task.correctValue), diff = Math.abs(value - expected), tolerance = Number(task.tolerance || 0); if (diff <= tolerance) return 1; var near = Number(task.nearTolerance || Math.max(1, Math.abs(expected) * 0.1)); return diff <= near ? 0.5 : 0; }
  return 0;
}
function taskReviewTargets(task, answer) {
  var out = new Set(list(task.reviewTargets)), options = list(task.options);
  if (task.kind === 'multi') { var selected = new Set(Array.isArray(answer) ? answer : []); options.forEach(function (option) { if ((selected.has(option.id) && !option.correct) || (!selected.has(option.id) && option.correct)) list(option.reviewTargets).forEach(function (target) { out.add(target); }); }); }
  else if (options.length) { var chosen = options.find(function (option) { return option.id === answer; }); if (chosen && !chosen.correct) list(chosen.reviewTargets).forEach(function (target) { out.add(target); }); }
  return Array.from(out);
}
function renderAnswered(container, task, stageState, nextLabel, nextFn) {
  var extra = '';
  if (task.kind === 'order') { var correctText = list(task.correctOrder).map(function (id) { var item = list(task.items).find(function (row) { return row.id === id; }); return esc(item ? item.text : id); }).join(' → '); extra = '<div class="feedback ' + (stageState.ratio === 1 ? 'good' : 'bad') + '">Правильная последовательность: ' + correctText + '</div>'; }
  if (task.kind === 'number') extra = '<div class="feedback ' + (stageState.ratio === 1 ? 'good' : 'bad') + '">Ожидаемый результат: ' + esc(task.correctValue) + ' ' + esc(task.unit || '') + '</div>';
  container.innerHTML = '<div class="card solve-task answered"><div class="tag">' + esc(task.category) + ' · ' + Math.round(stageState.ratio * 100) + '%</div><h3>' + esc(task.prompt) + '</h3>' + selectedFeedback(task, stageState.answer) + extra + '<div class="stage-score"><b>' + Math.round(stageState.earned) + '/' + Math.round(stageState.max) + '</b><span>баллов этапа</span></div><button class="primary" id="nextCaseStage">' + esc(nextLabel) + '</button></div>';
  container.querySelector('#nextCaseStage').onclick = nextFn;
}
function bindNotebook(modal, caseData) { var textarea = modal.querySelector('#caseNotebook'), timer = null; if (!textarea) return; textarea.oninput = function () { clearTimeout(timer); timer = setTimeout(function () { saveCaseNotebook(caseData.id, textarea.value); }, 150); }; }
function debriefHTML(caseData, result, related) {
  var d = caseData.debrief || {}, cats = result.categories || {};
  var categoryHtml = Object.keys(cats).map(function (key) { var value = cats[key]; return '<div class="card"><span>' + esc(key) + '</span><b>' + value + '%</b><div class="progress"><i style="width:' + value + '%"></i></div></div>'; }).join('');
  var rows = [['1. Главная проблема', d.mainIssue], ['2. Юридическая квалификация', d.qualification], ['3. Важные факты', list(d.importantFacts).join(' · ')], ['4. Что было шумом', list(d.noiseFacts).join(' · ')], ['5. Правильная последовательность', list(d.sequence).join(' → ')], ['6. Документы и evidence', list(d.documents).join(' · ')], ['7. Допустимые альтернативы', list(d.alternatives).join(' · ')], ['8. Почему слабые стратегии хуже', d.whyOthersWorse], ['9. Основные риски', list(d.risks).join(' · ')]];
  var sections = rows.filter(function (row) { return row[1]; }).map(function (row) { return '<div class="card legal-card"><h3>' + row[0] + '</h3><p>' + esc(row[1]) + '</p></div>'; }).join('');
  var sources = list(caseData.sources).map(function (source) { return '<a href="' + source.url + '" target="_blank" rel="noopener">' + esc(source.name) + ': ' + esc(source.title) + ' ↗</a>'; }).join('');
  var reviewLinks = list(caseData.relatedSubtopics).map(function (item) { return '<button class="secondary" data-review-lesson="' + esc(item.lessonId) + '" data-review-target="' + esc(item.target) + '">' + esc(item.label || item.target) + '</button>'; }).join('');
  var relatedHtml = related.map(function (item) { return '<button data-lesson="' + esc(item.id) + '"><b>' + esc(item.title) + '</b><br><span class="micro">LEARN · Knowledge Mastery</span></button>'; }).join('');
  return '<div class="case-result"><div class="case-score-hero card"><div><span>CASE SCORE</span><b>' + result.score + '/100</b><strong>' + scoreLabel(result.score) + '</strong></div>' + (result.earned ? '<div class="case-xp">+' + result.earned + ' XP</div>' : '<div class="case-xp muted">Practice run · XP уже получен</div>') + '</div><div class="category-scores">' + categoryHtml + '</div>' + (result.notebook ? '<div class="card legal-card"><h3>Ваш анализ</h3><p class="notebook-copy">' + esc(result.notebook) + '</p><div class="tag" style="margin-top:12px">Сравните с профессиональным разбором ниже</div></div>' : '') + '<section class="professional-debrief"><div class="tag">PROFESSIONAL DEBRIEF</div>' + sections + '</section><div class="card source-box"><div class="tag">10. Official sources</div>' + sources + '</div>' + (reviewLinks ? '<section class="section"><div class="tag">Что повторить</div><div class="review-links">' + reviewLinks + '</div></section>' : '') + (relatedHtml ? '<section class="section"><div class="tag">11. Связанные уроки</div><div class="linked">' + relatedHtml + '</div></section>' : '') + '<button class="secondary" data-restart-case style="width:100%;margin-top:14px">Пройти dossier снова</button></div>';
}

export async function openCase(id, ctx) {
  var c;
  try { c = await oneCase(id); } catch (error) { alert('Не удалось загрузить dossier'); return; }
  var rel = await relatedLessons(c.linkedLessons || []), allowed = usableStatus(c.status), history = viewCase(c.id), existing = activeCaseRun(c.id);
  var locked = allowed ? '' : '<div class="card legal-card blocked-content"><h3>' + (c.status === 'OUTDATED' ? 'Материал устарел' : 'Материал проходит юридическую проверку') + '</h3><p>Dossier виден в базе, но SOLVE недоступен до статуса CURRENT или UPDATED. Просмотр не создает attempt или score.</p></div>';
  var body = '<div class="eyebrow">SOLVE 2.0 · ' + esc(c.area) + '</div><h1 class="lesson-title">' + esc(c.title) + '</h1><div class="meta-chips">' + statusBadge(c.status) + '<span class="chip">' + esc(c.level) + ' · ' + (c.estimatedMinutes || 6) + ' мин</span><span class="chip">Practical XP +' + (c.xp || 20) + ' один раз</span>' + (history.completed ? '<span class="chip">Best ' + history.bestScore + '/100</span>' : '') + '</div>' + dossierHTML(c) + locked + (allowed ? notebookHTML(existing) : '') + '<div id="caseStage"></div>';
  var modal = modalBase('Практический dossier', list(c.tasks).length + ' этапов', body);
  if (!allowed) return;
  bindNotebook(modal, c);
  var stage = modal.querySelector('#caseStage'), stageIndex = existing ? existing.currentStage : 0;
  function finish() { var result = finishCaseV2(c); stage.innerHTML = debriefHTML(c, result, rel); stage.querySelectorAll('[data-lesson]').forEach(function (button) { button.onclick = function () { ctx.openLesson(button.dataset.lesson); }; }); stage.querySelectorAll('[data-review-lesson]').forEach(function (button) { button.onclick = function () { ctx.openLesson(button.dataset.reviewLesson, button.dataset.reviewTarget); }; }); var restart = stage.querySelector('[data-restart-case]'); if (restart) restart.onclick = function () { restartCaseRun(c.id); stageIndex = 0; var textarea = modal.querySelector('#caseNotebook'); if (textarea) textarea.value = ''; render(); }; if (ctx.refresh) ctx.refresh(); }
  function next() { stageIndex += 1; if (stageIndex >= list(c.tasks).length) { finish(); return; } setCaseStage(c.id, stageIndex); render(); }
  function ensureRun() { var run = ensureCaseRun(c.id); if (stageIndex !== run.currentStage) stageIndex = run.currentStage; return run; }
  function submit(task, answer) { ensureRun(); var ratio = stageRatio(task, answer), max = Number(task.weight || 0); var result = submitCaseStage(c.id, task.id, { earned: max * ratio, max: max, category: task.category || 'Reasoning', answer: answer, wrongAttempts: ratio < 1 ? 1 : 0, reviewTargets: taskReviewTargets(task, answer) }); renderAnswered(stage.querySelector('#taskInner'), task, result, stageIndex === list(c.tasks).length - 1 ? 'Показать профессиональный разбор' : 'Следующий этап', next); if (ctx.refresh) ctx.refresh(); }
  function renderMulti(inner, task, draft) { var selected = new Set(Array.isArray(draft) ? draft : []); inner.innerHTML = '<div class="card solve-task"><div class="tag">' + esc(task.category) + ' · ' + task.weight + ' баллов</div><h3>' + esc(task.prompt) + '</h3><p class="micro">Можно выбрать несколько вариантов.</p><div class="solve-options">' + list(task.options).map(function (option) { return '<button class="option ' + (selected.has(option.id) ? 'sel' : '') + '" data-case-option="' + esc(option.id) + '">' + esc(option.text) + '</button>'; }).join('') + '</div><button class="primary" id="submitCaseTask">Зафиксировать анализ</button></div>'; inner.querySelectorAll('[data-case-option]').forEach(function (button) { button.onclick = function () { ensureRun(); var oid = button.dataset.caseOption; if (selected.has(oid)) selected.delete(oid); else selected.add(oid); saveCaseDraft(c.id, task.id, Array.from(selected)); button.classList.toggle('sel', selected.has(oid)); }; }); inner.querySelector('#submitCaseTask').onclick = function () { submit(task, Array.from(selected)); }; }
  function renderSingle(inner, task, draft) { var current = draft || ''; inner.innerHTML = '<div class="card solve-task"><div class="tag">' + esc(task.category) + ' · ' + task.weight + ' баллов</div><h3>' + esc(task.prompt) + '</h3><div class="solve-options">' + list(task.options).map(function (option) { return '<button class="option ' + (current === option.id ? 'sel' : '') + '" data-case-option="' + esc(option.id) + '">' + esc(option.text) + '</button>'; }).join('') + '</div><button class="primary" id="submitCaseTask" ' + (current ? '' : 'disabled') + '>Зафиксировать решение</button></div>'; inner.querySelectorAll('[data-case-option]').forEach(function (button) { button.onclick = function () { ensureRun(); current = button.dataset.caseOption; saveCaseDraft(c.id, task.id, current); inner.querySelectorAll('[data-case-option]').forEach(function (node) { node.classList.toggle('sel', node === button); }); inner.querySelector('#submitCaseTask').disabled = false; }; }); inner.querySelector('#submitCaseTask').onclick = function () { submit(task, current); }; }
  function renderOrder(inner, task, draft) { var order = Array.isArray(draft) ? draft.slice() : (Array.isArray(task.initialOrder) ? task.initialOrder.slice() : list(task.items).map(function (item) { return item.id; })); function draw() { inner.innerHTML = '<div class="card solve-task"><div class="tag">' + esc(task.category) + ' · ' + task.weight + ' баллов</div><h3>' + esc(task.prompt) + '</h3><div class="order-list">' + order.map(function (oid, index) { var item = list(task.items).find(function (row) { return row.id === oid; }); return '<div class="order-item"><span>' + (index + 1) + '</span><b>' + esc(item ? item.text : oid) + '</b><div><button data-up="' + index + '" aria-label="Вверх">↑</button><button data-down="' + index + '" aria-label="Вниз">↓</button></div></div>'; }).join('') + '</div><button class="primary" id="submitCaseTask">Зафиксировать порядок</button></div>'; inner.querySelectorAll('[data-up]').forEach(function (button) { button.onclick = function () { ensureRun(); var i = Number(button.dataset.up); if (i > 0) { var tmp = order[i - 1]; order[i - 1] = order[i]; order[i] = tmp; saveCaseDraft(c.id, task.id, order); draw(); } }; }); inner.querySelectorAll('[data-down]').forEach(function (button) { button.onclick = function () { ensureRun(); var i = Number(button.dataset.down); if (i < order.length - 1) { var tmp = order[i + 1]; order[i + 1] = order[i]; order[i] = tmp; saveCaseDraft(c.id, task.id, order); draw(); } }; }); inner.querySelector('#submitCaseTask').onclick = function () { submit(task, order.slice()); }; } draw(); }
  function renderNumber(inner, task, draft) { var current = draft == null ? '' : String(draft); inner.innerHTML = '<div class="card solve-task"><div class="tag">' + esc(task.category) + ' · ' + task.weight + ' баллов</div><h3>' + esc(task.prompt) + '</h3><div class="number-answer"><input id="caseNumber" inputmode="decimal" value="' + esc(current) + '" placeholder="Введите результат"><span>' + esc(task.unit || '') + '</span></div><button class="primary" id="submitCaseTask">Зафиксировать расчет</button></div>'; var input = inner.querySelector('#caseNumber'); input.oninput = function () { ensureRun(); current = input.value; saveCaseDraft(c.id, task.id, current); }; inner.querySelector('#submitCaseTask').onclick = function () { submit(task, current); }; }
  function render() { var run = activeCaseRun(c.id), task = list(c.tasks)[stageIndex]; if (!task) { if (run) finish(); return; } var saved = caseStageState(c.id, task.id); stage.innerHTML = progressHTML(c, run, stageIndex) + '<div id="taskInner"></div>'; var inner = stage.querySelector('#taskInner'); if (saved && saved.finalized) { renderAnswered(inner, task, saved, stageIndex === list(c.tasks).length - 1 ? 'Показать профессиональный разбор' : 'Следующий этап', next); return; } var drafts = run && run.drafts ? run.drafts : {}, draft = drafts[task.id]; if (draft === undefined) { if (task.kind === 'order') draft = Array.isArray(task.initialOrder) ? task.initialOrder.slice() : list(task.items).map(function (item) { return item.id; }); else if (task.kind === 'multi') draft = []; else draft = ''; } if (task.kind === 'multi') renderMulti(inner, task, draft); else if (task.kind === 'single') renderSingle(inner, task, draft); else if (task.kind === 'order') renderOrder(inner, task, draft); else if (task.kind === 'number') renderNumber(inner, task, draft); }
  render();
}
