import{stateSnapshot,replaceState}from'./state.js';

const SUPABASE_URL='https://nnexhmzebviispxkpclx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_91vY-4O1RkByvFz7IB_QPg_vwLt5AKN';
const SDK_URL='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const META_KEY='lexifrance-cloud-v1';
const QUEUE_KEY='lexifrance-sync-queue-v1';
const STATE_KEY='lexifrance-state-v5';
const MAX_QUEUE=24;
const clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
const safeParse=(v,fallback)=>{try{return JSON.parse(v??'')??fallback}catch{return fallback}};
const iso=()=>new Date().toISOString();
const uuid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}-${Math.random().toString(16).slice(2)}`;
const baseMeta=()=>({deviceId:uuid(),userId:null,isAnonymous:null,email:null,version:0,status:'local',pending:0,lastSyncAt:null,lastError:null,contentRelease:null,initialized:false});
let meta={...baseMeta(),...safeParse(localStorage.getItem(META_KEY),{})},client=null,starting=null,flushTimer=null,contentRelease=null,hydrateCallback=null,suppressQueue=false;
const listeners=new Set();
function persistMeta(){meta.pending=queue().length;localStorage.setItem(META_KEY,JSON.stringify(meta));for(const fn of listeners)try{fn(getCloudStatus())}catch{}}
function queue(){const q=safeParse(localStorage.getItem(QUEUE_KEY),[]);return Array.isArray(q)?q:[]}
function writeQueue(q){localStorage.setItem(QUEUE_KEY,JSON.stringify(q.slice(-MAX_QUEUE)));meta.pending=Math.min(q.length,MAX_QUEUE);persistMeta()}
function setStatus(status,error=null){meta.status=status;meta.lastError=error?String(error?.message||error):null;persistMeta()}
function localHasLearning(s){return Number(s?.xp)>0||(s?.completed?.length||0)>0||Object.keys(s?.lessonProgress||{}).length>0||Object.keys(s?.caseV2History||{}).length>0}
function latest(a,b){if(!a)return b;if(!b)return a;return String(a)>String(b)?a:b}
function earliest(a,b){if(!a)return b;if(!b)return a;return String(a)<String(b)?a:b}
function mergeQuestion(a={},b={}){return{...a,...b,solved:!!(a.solved||b.solved),attempts:Math.max(a.attempts||0,b.attempts||0),wrongAttempts:Math.max(a.wrongAttempts||0,b.wrongAttempts||0),firstAttemptCorrect:a.firstAttemptCorrect??b.firstAttemptCorrect??null,lastAnsweredAt:latest(a.lastAnsweredAt,b.lastAnsweredAt),solvedAt:earliest(a.solvedAt,b.solvedAt)}}
function mergeLesson(a={},b={}){const questions={};for(const id of new Set([...Object.keys(a.questions||{}),...Object.keys(b.questions||{})]))questions[id]=mergeQuestion(a.questions?.[id],b.questions?.[id]);const reviews=[...(a.reviews||[]),...(b.reviews||[])];const seen=new Set();return{...a,...b,opened:!!(a.opened||b.opened),openedAt:earliest(a.openedAt,b.openedAt),questions,xpClaimed:!!(a.xpClaimed||b.xpClaimed),lastAnsweredAt:latest(a.lastAnsweredAt,b.lastAnsweredAt),masteredAt:earliest(a.masteredAt,b.masteredAt),lastReviewAt:latest(a.lastReviewAt,b.lastReviewAt),nextReviewAt:latest(a.nextReviewAt,b.nextReviewAt),reviewIntervalIndex:Math.max(a.reviewIntervalIndex||0,b.reviewIntervalIndex||0),reviews:reviews.filter(r=>{const k=`${r?.date||''}|${r?.score||0}|${r?.firstTry||0}`;if(seen.has(k))return false;seen.add(k);return true}).sort((x,y)=>String(x?.date||'').localeCompare(String(y?.date||'')))}}
function mergeCase(a={},b={}){const active=[a.activeRun,b.activeRun].filter(Boolean).sort((x,y)=>String(x?.lastActionAt||x?.startedAt||'').localeCompare(String(y?.lastActionAt||y?.startedAt||''))).pop()||null;return{...a,...b,views:Math.max(a.views||0,b.views||0),attempts:Math.max(a.attempts||0,b.attempts||0),completedRuns:Math.max(a.completedRuns||0,b.completedRuns||0),bestScore:Math.max(a.bestScore||0,b.bestScore||0),lastScore:String(a.lastCompletedAt||'')>String(b.lastCompletedAt||'')?(a.lastScore||0):(b.lastScore||0),xpAwarded:!!(a.xpAwarded||b.xpAwarded),completed:!!(a.completed||b.completed),lastViewedAt:latest(a.lastViewedAt,b.lastViewedAt),lastCompletedAt:latest(a.lastCompletedAt,b.lastCompletedAt),activeRun:active}}
export function mergeProgress(local={},remote={}){if(!localHasLearning(local))return{...clone(remote),theme:local.theme||remote.theme,font:local.font||remote.font,currentPath:local.currentPath||remote.currentPath};const out={...clone(remote),...clone(local)};out.xp=Math.max(local.xp||0,remote.xp||0);out.streak=Math.max(local.streak||0,remote.streak||0);out.lastStudyDay=latest(local.lastStudyDay,remote.lastStudyDay);out.completed=[...new Set([...(remote.completed||[]),...(local.completed||[])])];out.saved=[...new Set([...(remote.saved||[]),...(local.saved||[])])];out.lessonProgress={};for(const id of new Set([...Object.keys(remote.lessonProgress||{}),...Object.keys(local.lessonProgress||{})]))out.lessonProgress[id]=mergeLesson(remote.lessonProgress?.[id],local.lessonProgress?.[id]);out.caseV2History={};for(const id of new Set([...Object.keys(remote.caseV2History||{}),...Object.keys(local.caseV2History||{})]))out.caseV2History[id]=mergeCase(remote.caseV2History?.[id],local.caseV2History?.[id]);out.quizRuns={...(remote.quizRuns||{}),...(local.quizRuns||{})};out.legacyMastery={...(remote.legacyMastery||{}),...(local.legacyMastery||{})};out.legacyCaseHistory={...(remote.legacyCaseHistory||{}),...(local.legacyCaseHistory||{})};return out}
function enqueueSnapshot(reason='state_change'){if(suppressQueue)return;const snapshot=stateSnapshot();const q=queue();const event={eventId:uuid(),entityType:'state',entityId:'lexifrance',operation:'replace_state',payload:snapshot,createdAt:iso(),syncStatus:'pending',reason,localRevision:(q.at(-1)?.localRevision||0)+1};const compact=q.filter(x=>x.entityType!=='state'||x.syncStatus!=='pending');compact.push(event);writeQueue(compact);scheduleFlush()}
function scheduleFlush(ms=450){clearTimeout(flushTimer);flushTimer=setTimeout(()=>flushCloud().catch(()=>{}),ms)}
async function loadSdk(){if(client)return client;const mod=await import(SDK_URL);client=mod.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
async function establishSession(){const c=await loadSdk();let{data:{session},error}=await c.auth.getSession();if(error)throw error;if(!session){const res=await c.auth.signInAnonymously();if(res.error)throw res.error;session=res.data.session}if(!session)throw new Error('Supabase session unavailable');meta.userId=session.user.id;meta.isAnonymous=!!session.user.is_anonymous;meta.email=session.user.email||null;persistMeta();return session}
async function hydrate(){const c=await loadSdk();const{data,error}=await c.from('user_state').select('state,state_version,updated_at,content_release').maybeSingle();if(error)throw error;const local=stateSnapshot();if(!data){enqueueSnapshot('initial_local_migration');return}meta.version=Number(data.state_version)||0;const merged=mergeProgress(local,data.state||{});suppressQueue=true;try{replaceState(merged,{emit:false});}finally{suppressQueue=false}hydrateCallback?.();const differs=JSON.stringify(merged)!==JSON.stringify(data.state||{});if(differs)enqueueSnapshot('merge_local_cloud');else{meta.lastSyncAt=iso();persistMeta()}}
export async function flushCloud(){if(!navigator.onLine||!client||!meta.userId)return false;let q=queue();if(!q.length){setStatus('synced');return true}setStatus('syncing');for(let guard=0;guard<8&&q.length;guard++){const event=q[0];try{const{data,error}=await client.rpc('save_user_state',{p_expected_version:Number(meta.version)||0,p_event_id:event.eventId,p_payload:event.payload,p_device_id:meta.deviceId,p_content_release:contentRelease||meta.contentRelease});if(error)throw error;if(!data)throw new Error('Empty sync response');if(data.status==='conflict'){meta.version=Number(data.version)||0;const merged=mergeProgress(event.payload,data.state||{});suppressQueue=true;try{replaceState(merged,{emit:false})}finally{suppressQueue=false}hydrateCallback?.();event.eventId=uuid();event.payload=merged;event.createdAt=iso();event.syncStatus='pending';event.reason='conflict_merge';q[0]=event;writeQueue(q);continue}if(data.status==='ok'||data.status==='duplicate'){meta.version=Number(data.version)||meta.version;meta.lastSyncAt=iso();q.shift();writeQueue(q);continue}throw new Error(`Unknown sync status: ${data.status}`)}catch(e){event.syncStatus='pending';q[0]=event;writeQueue(q);setStatus('error',e);return false}}setStatus(q.length?'pending':'synced');return q.length===0}
export async function initCloud(opts={}){if(starting)return starting;contentRelease=opts.contentRelease||null;hydrateCallback=opts.onHydrate||null;meta.contentRelease=contentRelease;starting=(async()=>{window.addEventListener('lexifrance:state-saved',()=>enqueueSnapshot('local_save'));window.addEventListener('online',()=>{setStatus('connecting');initCloud(opts).then(()=>flushCloud())});window.addEventListener('offline',()=>setStatus('offline'));if(!navigator.onLine){setStatus('offline');meta.initialized=true;persistMeta();return getCloudStatus()}try{setStatus('connecting');const c=await loadSdk();await establishSession();c.auth.onAuthStateChange((_event,session)=>{if(session?.user){meta.userId=session.user.id;meta.isAnonymous=!!session.user.is_anonymous;meta.email=session.user.email||null;persistMeta()}else{meta.userId=null;meta.isAnonymous=null;meta.email=null;setStatus('local')}});await hydrate();await flushCloud();meta.initialized=true;persistMeta();return getCloudStatus()}catch(e){meta.initialized=true;setStatus('local_only',e);return getCloudStatus()}})();return starting}
export async function requestAccountUpgrade(email){const value=String(email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(value))throw new Error('Введите корректный email');const c=await loadSdk();const{data:{session}}=await c.auth.getSession();let error;if(session?.user?.is_anonymous){({error}=await c.auth.updateUser({email:value},{emailRedirectTo:location.href}))}else if(session){({error}=await c.auth.updateUser({email:value},{emailRedirectTo:location.href}))}else{({error}=await c.auth.signInWithOtp({email:value,options:{emailRedirectTo:location.href,shouldCreateUser:true}}))}if(error)throw error;meta.email=value;setStatus('verification_sent');return true}
export async function signOutCloud(){if(!client)return;await flushCloud();await client.auth.signOut();meta={...baseMeta(),deviceId:meta.deviceId,contentRelease};persistMeta();setStatus('local')}
export function getCloudStatus(){return{...meta,pending:queue().length,online:navigator.onLine,mode:meta.userId?(meta.isAnonymous?'anonymous':'account'):'local'}}
export function subscribeCloud(fn){listeners.add(fn);return()=>listeners.delete(fn)}
export function queueStateForSync(reason='manual'){enqueueSnapshot(reason);return flushCloud()}
export function cloudConfigured(){return Boolean(SUPABASE_URL&&SUPABASE_PUBLISHABLE_KEY&&!SUPABASE_PUBLISHABLE_KEY.includes('service_role'))}
