const SUPABASE_URL='https://nnexhmzebviispxkpclx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_91vY-4O1RkByvFz7IB_QPg_vwLt5AKN';
const PROJECT_REF='nnexhmzebviispxkpclx';
const META_KEY='lexifrance-cloud-v1';
const LOCAL_HOSTS=new Set(['localhost','127.0.0.1','::1']);
let observer=null,activeCloud=false,lastOptions=null,reconnectArmed=false;
const safeParse=(v,f={})=>{try{return JSON.parse(v||'')||f}catch{return f}};
export function cloudRuntimeAllowed(){if(!LOCAL_HOSTS.has(location.hostname))return true;return new URLSearchParams(location.search).get('cloud')==='live'}
function sessionHint(){if(location.hash.includes('access_token=')||location.hash.includes('refresh_token=')||location.search.includes('code='))return true;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(k===`sb-${PROJECT_REF}-auth-token`||k.startsWith(`sb-${PROJECT_REF}-auth-token.`))return true}return false}
function writeGuestMeta(status='guest_local',error=null){const old=safeParse(localStorage.getItem(META_KEY),{});localStorage.setItem(META_KEY,JSON.stringify({...old,status,userId:null,isAnonymous:null,email:old.email||null,initialized:true,anonymousReady:false,lastError:error?String(error):null}))}
async function authCapabilities(){if(!navigator.onLine)return{anonymous:false,offline:true};try{const r=await fetch(`${SUPABASE_URL}/auth/v1/settings`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`Auth settings HTTP ${r.status}`);const data=await r.json();return{anonymous:!!data?.external?.anonymous_users,email:!!data?.external?.email,offline:false}}catch(e){return{anonymous:false,email:true,offline:false,error:e}}}
async function startCloud(opts){if(activeCloud)return;activeCloud=true;document.querySelectorAll('[data-cloud-gate-panel]').forEach(x=>x.remove());const mod=await import('./cloud.js');return mod.initCloud(opts)}
function armReconnect(){if(reconnectArmed)return;reconnectArmed=true;window.addEventListener('online',async()=>{reconnectArmed=false;if(activeCloud)return;try{await initCloudGate(lastOptions||{})}catch{}},{once:true})}
function guestPanelHTML(){return `<section class="section cloud-account" data-cloud-gate-panel><div class="section-head"><div class="section-title"><div class="section-num">00</div><h2>Облачный прогресс</h2></div><div class="section-meta">Guest</div></div><div class="card legal-card"><div class="tag">Локально</div><h3>Начните без регистрации</h3><p>Прогресс надежно сохраняется на этом устройстве. В production LexiFrance создает anonymous cloud ID автоматически; email можно привязать позже для восстановления на другом устройстве.</p><label class="small" for="cloudGateEmail">Email для облачного аккаунта</label><div class="search-box" style="margin-top:6px"><input id="cloudGateEmail" type="email" inputmode="email" autocomplete="email" placeholder="email@example.com"></div><button class="primary" data-cloud-gate-upgrade style="margin-top:8px">Сохранить прогресс в облаке</button><div class="small" data-cloud-gate-message style="margin-top:6px"></div></div></section>`}
async function sendEmail(panel){const input=panel.querySelector('#cloudGateEmail'),button=panel.querySelector('[data-cloud-gate-upgrade]'),msg=panel.querySelector('[data-cloud-gate-message]');button.disabled=true;if(msg)msg.textContent='Отправляем подтверждение...';try{const mod=await import('./cloud.js');await mod.requestAccountUpgrade(input.value);if(msg)msg.textContent='Проверьте email. После подтверждения этот локальный прогресс будет синхронизирован.';setTimeout(()=>panel.remove(),1200)}catch(e){if(msg)msg.textContent=e?.message||'Не удалось отправить письмо. Локальный прогресс сохранен.'}finally{button.disabled=false}}
function mountGuestPanel(){if(activeCloud||(location.hash||'#home')!=='#profile')return;const root=document.querySelector('#root'),anchor=root?.querySelector('.profile-grid');if(!anchor||root.querySelector('[data-cloud-gate-panel]')||root.querySelector('[data-cloud-panel]'))return;anchor.insertAdjacentHTML('afterend',guestPanelHTML());const panel=root.querySelector('[data-cloud-gate-panel]');panel?.querySelector('[data-cloud-gate-upgrade]')?.addEventListener('click',()=>sendEmail(panel))}
function observeGuestPanel(){if(observer)return;observer=new MutationObserver(()=>mountGuestPanel());observer.observe(document.querySelector('#root')||document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mountGuestPanel,0));mountGuestPanel()}
export async function initCloudGate(opts={}){lastOptions=opts;observeGuestPanel();if(!cloudRuntimeAllowed()){writeGuestMeta('qa_local');mountGuestPanel();return{status:'qa_local',mode:'local',anonymousReady:false,emailReady:false}}if(sessionHint())return startCloud(opts);if(!navigator.onLine){writeGuestMeta('offline');armReconnect();return{status:'offline',mode:'local'}};const caps=await authCapabilities();if(caps.anonymous)return startCloud(opts);writeGuestMeta(caps.error?'local_only':'guest_local',caps.error||null);armReconnect();mountGuestPanel();return{status:caps.error?'local_only':'guest_local',mode:'local',anonymousReady:false,emailReady:caps.email!==false}}
export{authCapabilities};
