const SUPABASE_URL='https://nnexhmzebviispxkpclx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_91vY-4O1RkByvFz7IB_QPg_vwLt5AKN';
const LOCAL_HOSTS=new Set(['localhost','127.0.0.1','::1']);
const AREAS=['Corporate','Tax','Immigration','Real Estate'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let observer=null,timer=null,requestSeq=0;
function remoteAllowed(){if(!navigator.onLine)return false;if(!LOCAL_HOSTS.has(location.hostname))return true;return new URLSearchParams(location.search).get('rag')==='live'}
function inferArea(query){const q=String(query||'').toLowerCase();if(/oqtf|titre|séjour|sejour|préfect|prefect|visa|immig|naturalisa/.test(q))return'Immigration';if(/tva|impôt|impot|fiscal|pfu|is\b|ir\b|tax/.test(q))return'Tax';if(/bail|locat|loyer|immeuble|immobilier|sci|dépôt de garantie|depot de garantie|urbanisme/.test(q))return'Real Estate';if(/sasu|sas\b|sarl|eurl|capital|associé|associe|statuts|cca|dividende|cession/.test(q))return'Corporate';return null}
async function sameOriginApi(query,area,limit){try{const r=await fetch('./api/legal-search',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({query,area,limit}),cache:'no-store'});if(!r.ok)return null;const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))return null;const data=await r.json();if(!Array.isArray(data?.rows))return null;return{rows:data.rows,mode:data.mode||'server',semanticUsed:!!data.semanticUsed}}catch{return null}}
async function supabaseLexical(query,area,limit){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/hybrid_legal_search`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({p_query_text:query,p_query_embedding:null,p_legal_area:area||null,p_as_of:new Date().toISOString().slice(0,10),p_official_only:true,p_limit:limit}),cache:'no-store'});if(!r.ok)return null;const rows=await r.json();return{rows:Array.isArray(rows)?rows:[],mode:'verified-lexical',semanticUsed:false}}catch{return null}}
export async function verifiedLegalSearch(query,{area=null,limit=6}={}){const q=String(query||'').trim();if(q.length<2||!remoteAllowed())return{rows:[],mode:navigator.onLine?'local-only':'offline',semanticUsed:false};const legalArea=AREAS.includes(area)?area:inferArea(q);const api=await sameOriginApi(q,legalArea,limit);if(api)return api;return await supabaseLexical(q,legalArea,limit)||{rows:[],mode:'unavailable',semanticUsed:false}}
function sourceCard(row,index){const article=row.source_article?` · ${esc(row.source_article)}`:'';const score=Math.max(0,Math.min(100,Math.round((Number(row.combined_score)||0)*100)));return `<article class="card result-row legal-source-result"><div class="tag">SOURCE ${index+1} · ${esc(row.legal_area||'FR')} · ${esc(row.source_status||'CURRENT')}${article}</div><h3>${esc(row.section||row.source_title||'Source officielle')}</h3><p>${esc(row.content||'')}</p><div class="small">Vérifié: ${esc(String(row.verified_at||'').slice(0,10))}${score?` · relevance ${score}%`:''}</div><a href="${esc(row.source_url)}" target="_blank" rel="noopener">${esc(row.source_title||'Открыть официальный источник')}</a></article>`}
function ensurePanel(root){let panel=root.querySelector('[data-verified-legal-search]');if(panel)return panel;const results=root.querySelector('#searchResults');if(!results)return null;results.insertAdjacentHTML('afterend','<section class="section" data-verified-legal-search><div class="section-head"><div class="section-title"><div class="section-num">RAG</div><h2>Проверенные источники</h2></div><div class="section-meta" data-rag-mode>Deterministic first</div></div><p class="page-copy">Основной поиск LexiFrance остается детерминированным. Этот слой добавляет только CURRENT / UPDATED официальные источники с проверкой effective date.</p><div data-rag-results class="result-list"></div></section>');return root.querySelector('[data-verified-legal-search]')}
async function renderQuery(root,query){const panel=ensurePanel(root);if(!panel)return;const out=panel.querySelector('[data-rag-results]'),mode=panel.querySelector('[data-rag-mode]');const q=query.trim();if(q.length<2){out.innerHTML='';mode.textContent='Deterministic first';return}const seq=++requestSeq;mode.textContent=navigator.onLine?'Проверяем источники…':'Offline fallback';if(!navigator.onLine){out.innerHTML='<div class="small">Offline: используется основной детерминированный Search. Проверенные cloud-source chunks будут доступны после reconnect.</div>';return}const result=await verifiedLegalSearch(q,{limit:6});if(seq!==requestSeq)return;mode.textContent=result.semanticUsed?'Hybrid semantic + keyword':result.mode==='verified-lexical'?'Verified keyword':'Verified fallback';out.innerHTML=result.rows.length?result.rows.map(sourceCard).join(''):'<div class="small">Дополнительных CURRENT/UPDATED source chunks по этому запросу не найдено. Основные результаты выше остаются доступны.</div>'}
function bind(root){if((location.hash||'#home')!=='#search')return;const input=root.querySelector('#searchInput');if(!input||input.dataset.verifiedLegalBound)return;input.dataset.verifiedLegalBound='1';ensurePanel(root);input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>renderQuery(root,input.value),260)});if(input.value)renderQuery(root,input.value)}
export function initVerifiedLegalSearch(){const root=document.querySelector('#root');if(!root)return;observer=new MutationObserver(()=>bind(root));observer.observe(root,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(()=>bind(root),0));window.addEventListener('online',()=>{if((location.hash||'#home')==='#search'){const input=root.querySelector('#searchInput');if(input?.value)renderQuery(root,input.value)}});bind(root)}
initVerifiedLegalSearch();
