const KEY='lexifrance-state-v5';
const LEGACY_KEYS=['lexifrance-state-v4','lexifrance-state-v3','lexifrance-state-v2','lexifrance-state'];
const REVIEW_INTERVALS=[7,30,90];
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toISOString();
const dateOnly=v=>v?String(v).slice(0,10):null;
const days=(a,b=today())=>a?Math.floor((new Date(`${dateOnly(b)}T00:00:00Z`)-new Date(`${dateOnly(a)}T00:00:00Z`))/86400000):9999;
const addDays=(iso,n)=>{const d=new Date(iso||now());d.setUTCDate(d.getUTCDate()+n);return d.toISOString()};
const clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
const base=()=>({xp:0,streak:0,lastStudyDay:null,completed:[],saved:[],lessonProgress:{},legacyMastery:{},quizRuns:{},caseV2History:{},legacyCaseHistory:{},name:'',theme:'light',font:16,currentPath:'Corporate',currentLesson:null,migratedCourseV5:false,migratedSolveV2:false});
function safeParse(raw){try{return JSON.parse(raw||'null')}catch{return null}}
function load(){const current=safeParse(localStorage.getItem(KEY));if(current)return{...base(),...current};for(const k of LEGACY_KEYS){const s=safeParse(localStorage.getItem(k));if(s){const merged={...base(),...s};if(merged.name==='Petr')merged.name='';return merged}}return base()}
export const state=load();
export function save(){localStorage.setItem(KEY,JSON.stringify(state))}
export function applyPrefs(){document.body.classList.toggle('dark',state.theme==='dark');document.documentElement.style.setProperty('--body-size',`${state.font||16}px`)}
export function setTheme(v){state.theme=v;save();applyPrefs()}
export function setFont(delta){state.font=Math.max(16,Math.min(20,(state.font||16)+delta));save();applyPrefs()}
function emptyQuestion(){return{solved:false,attempts:0,wrongAttempts:0,firstAttemptCorrect:null,lastAnsweredAt:null,solvedAt:null}}
function emptyLesson(){return{opened:false,openedAt:null,mastery:0,questions:{},xpClaimed:false,lastAnsweredAt:null,masteredAt:null,lastReviewAt:null,nextReviewAt:null,reviewIntervalIndex:0,reviews:[]}}
function masteryFrom(p){const solved=Object.values(p.questions||{}).filter(q=>q?.solved).length;return Math.min(100,(p.opened?10:0)+(solved*9))}
function normalizeLesson(p={}){const out={...emptyLesson(),...p,questions:{...(p.questions||{})},reviews:[...(p.reviews||[])]};out.mastery=masteryFrom(out);if(out.mastery===100&&!out.masteredAt)out.masteredAt=out.lastAnsweredAt||out.openedAt||now();if(out.mastery===100&&!out.nextReviewAt)out.nextReviewAt=addDays(out.masteredAt,REVIEW_INTERVALS[0]);return out}
export function lessonProgress(id){if(!state.lessonProgress[id])state.lessonProgress[id]=emptyLesson();const p=normalizeLesson(state.lessonProgress[id]);state.lessonProgress[id]=p;return p}
export function mastery(id){const p=lessonProgress(id);return{score:masteryFrom(p),opened:p.opened,solved:Object.values(p.questions||{}).filter(q=>q?.solved).length}}
export function masteryLabel(score){if(score>=100)return['Mastered','Освоено',5];if(score>=73)return['Confident','Уверенное знание',4];if(score>=46)return['Understood','Понимаете',3];if(score>=19)return['Learning','Изучаете',2];if(score>=10)return['Seen','Открыто',1];return['New','Не начато',0]}
export function migrateCourseV5(map={}){if(state.migratedCourseV5)return;const oldMastery=state.mastery||{};state.legacyMastery={...(state.legacyMastery||{}),...oldMastery};const oldCompleted=[...(state.completed||[])];const oldSaved=[...(state.saved||[])];const mappedCompleted=[...new Set(oldCompleted.map(id=>map[id]||id))];const mappedSaved=[...new Set(oldSaved.map(id=>map[id]||id))];const touched=new Set([...Object.keys(oldMastery).map(id=>map[id]||id),...mappedCompleted,...mappedSaved]);for(const id of touched){const p=lessonProgress(id);const legacyIds=Object.keys(oldMastery).filter(x=>(map[x]||x)===id);const legacyScore=Math.max(0,...legacyIds.map(x=>oldMastery[x]?.score||0));if(legacyScore>=10||mappedCompleted.includes(id)){p.opened=true;p.openedAt=p.openedAt||now()}if(mappedCompleted.includes(id))p.xpClaimed=true;p.mastery=masteryFrom(p);state.lessonProgress[id]=p}state.completed=mappedCompleted;state.saved=mappedSaved;if(state.currentLesson)state.currentLesson=map[state.currentLesson]||state.currentLesson;if(state.name==='Petr')state.name='';delete state.mastery;delete state.quizResults;state.migratedCourseV5=true;save()}
export function migrateSolveV2(){if(state.migratedSolveV2)return;if(state.caseHistory&&Object.keys(state.caseHistory).length&&!Object.keys(state.legacyCaseHistory||{}).length)state.legacyCaseHistory=clone(state.caseHistory);delete state.caseHistory;state.caseV2History=state.caseV2History||{};state.quizRuns=state.quizRuns||{};state.migratedSolveV2=true;save()}
function studyDay(){const t=today();if(state.lastStudyDay===t)return;if(state.lastStudyDay&&days(state.lastStudyDay,t)===1)state.streak=(state.streak||0)+1;else state.streak=1;state.lastStudyDay=t}
export function openLessonProgress(id,allowed=true){const p=lessonProgress(id);if(!allowed)return{first:false,score:p.mastery,blocked:true};const first=!p.opened;if(first){p.opened=true;p.openedAt=now();p.mastery=masteryFrom(p)}state.currentLesson=id;save();return{first,score:p.mastery,blocked:false}}
export function answerQuestion(lessonId,questionId,correct,lessonXp=0){const p=lessonProgress(lessonId);if(!p.opened){p.opened=true;p.openedAt=now()}const before=masteryFrom(p);const q={...emptyQuestion(),...(p.questions[questionId]||{})};q.attempts+=1;if(q.firstAttemptCorrect===null)q.firstAttemptCorrect=!!correct;if(!correct)q.wrongAttempts+=1;q.lastAnsweredAt=now();let newlySolved=false;if(correct&&!q.solved){q.solved=true;q.solvedAt=now();newlySolved=true;studyDay()}p.questions[questionId]=q;p.lastAnsweredAt=q.lastAnsweredAt;p.mastery=masteryFrom(p);let earned=0,completedNow=false;if(p.mastery===100&&!p.masteredAt){p.masteredAt=now();p.nextReviewAt=addDays(p.masteredAt,REVIEW_INTERVALS[0]);p.reviewIntervalIndex=0}if(p.mastery===100&&!p.xpClaimed){p.xpClaimed=true;earned=lessonXp||0;state.xp+=earned;completedNow=true;if(!state.completed.includes(lessonId))state.completed.push(lessonId)}else if(p.mastery===100&&!state.completed.includes(lessonId))state.completed.push(lessonId);save();return{correct,newlySolved,before,after:p.mastery,earned,completedNow,question:{...q}}}
export function questionProgress(lessonId,questionId){return{...emptyQuestion(),...(lessonProgress(lessonId).questions[questionId]||{})}}
export function pathMastery(ids){if(!ids?.length)return 0;return Math.round(ids.reduce((sum,id)=>sum+mastery(id).score,0)/ids.length)}
export function knowledgeFreshness(id){const p=lessonProgress(id),score=masteryFrom(p);if(score<100)return{state:'learning',due:false,label:'Еще изучается',lastReviewAt:p.lastReviewAt,nextReviewAt:null,daysSince:null};const ref=p.lastReviewAt||p.masteredAt||p.lastAnsweredAt||p.openedAt;const next=p.nextReviewAt||addDays(ref,REVIEW_INTERVALS[Math.min(p.reviewIntervalIndex||0,2)]);const due=Date.now()>=new Date(next).getTime();const since=days(ref);return{state:due?'due':'fresh',due,label:due?'Пора повторить':'Знание свежее',lastReviewAt:p.lastReviewAt||p.masteredAt,nextReviewAt:next,daysSince:since}}
export function dueReviews(ids){return(ids||[]).filter(id=>{const p=lessonProgress(id),m=masteryFrom(p);if(!p.opened)return false;if(m===100)return knowledgeFreshness(id).due;return !!p.lastAnsweredAt&&days(p.lastAnsweredAt)>=7})}
export function recordQuizReview(lessonId,result){if(mastery(lessonId).score<100)return{recorded:false,due:false};const freshness=knowledgeFreshness(lessonId),p=lessonProgress(lessonId),due=!!result.dueAtStart||freshness.due,entry={date:now(),score:result.score??0,firstTry:result.firstTry??0,errors:result.errors??0,weakTopics:[...(result.weakTopics||[])],due};p.reviews.push(entry);p.lastReviewAt=entry.date;if(due){p.reviewIntervalIndex=Math.min(2,(p.reviewIntervalIndex||0)+1);p.nextReviewAt=addDays(entry.date,REVIEW_INTERVALS[p.reviewIntervalIndex])}save();return{recorded:true,due,nextReviewAt:p.nextReviewAt}}
export function recentWeakTargets(){const rows=[];for(const [lessonId,p] of Object.entries(state.lessonProgress||{})){for(const r of (p.reviews||[]).slice(-3)){for(const w of r.weakTopics||[])if(w?.target)rows.push({lessonId,target:w.target,date:r.date})}}for(const [lessonId,r] of Object.entries(state.quizRuns||{})){for(const target of Object.keys(r?.wrongTargets||{}))rows.push({lessonId,target,date:r.startedAt||now()})}return[...new Map(rows.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>[x.target,x])).values()].slice(0,12).map(x=>x.target)}
export function getQuizRun(lessonId){return state.quizRuns?.[lessonId]||null}
export function saveQuizRun(lessonId,run){state.quizRuns=state.quizRuns||{};state.quizRuns[lessonId]=run;save()}
export function clearQuizRun(lessonId){if(state.quizRuns)delete state.quizRuns[lessonId];save()}
export function toggleSaved(id){const i=state.saved.indexOf(id);if(i>=0)state.saved.splice(i,1);else state.saved.push(id);save();return i<0}
function emptyCaseV2(){return{views:0,attempts:0,completedRuns:0,bestScore:0,lastScore:0,xpAwarded:false,completed:false,lastViewedAt:null,lastCompletedAt:null,activeRun:null}}
export function caseV2Progress(id){if(!state.caseV2History[id])state.caseV2History[id]=emptyCaseV2();const h=state.caseV2History[id],d=emptyCaseV2();for(const[k,v]of Object.entries(d))if(h[k]===undefined)h[k]=v;return h}
export function viewCase(id){const h=caseV2Progress(id);h.views+=1;h.lastViewedAt=now();save();return h}
function newCaseRun(h,id){h.attempts+=1;const t=now();h.activeRun={id:`${id}-run-${h.attempts}`,startedAt:t,currentStage:0,stageStates:{},drafts:{},scoreByCategory:{},pointsEarned:0,pointsMax:0,wrongAttempts:0,notebook:'',finished:false,lastActionAt:t};return h.activeRun}
export function activeCaseRun(id){return caseV2Progress(id).activeRun}
export function ensureCaseRun(id){const h=caseV2Progress(id);if(h.activeRun&&!h.activeRun.finished)return h.activeRun;const run=newCaseRun(h,id);save();return run}
export function restartCaseRun(id){const h=caseV2Progress(id);if(h.activeRun)h.activeRun.finished=true;const run=newCaseRun(h,id);save();return run}
export function setCaseStage(id,index){const run=ensureCaseRun(id);run.currentStage=Math.max(0,index);run.lastActionAt=now();save();return run}
export function saveCaseNotebook(id,text){const run=ensureCaseRun(id);run.notebook=String(text||'').slice(0,8000);run.lastActionAt=now();save();return run.notebook}
export function saveCaseDraft(id,stageId,value){const run=ensureCaseRun(id);run.drafts=run.drafts||{};run.drafts[stageId]=clone(value);run.lastActionAt=now();save();return value}
export function caseStageState(id,stageId){return activeCaseRun(id)?.stageStates?.[stageId]||null}
export function submitCaseStage(caseId,stageId,result){const run=ensureCaseRun(caseId);if(run.stageStates[stageId]?.finalized)return{...run.stageStates[stageId],duplicate:true};const earned=Math.max(0,Number(result.earned)||0),max=Math.max(0,Number(result.max)||0),category=result.category||'Reasoning';const st={finalized:true,earned,max,ratio:max?earned/max:0,answer:clone(result.answer),feedback:result.feedback||'',wrongAttempts:Number(result.wrongAttempts)||0,completedAt:now(),reviewTargets:[...(result.reviewTargets||[])]};run.stageStates[stageId]=st;run.pointsEarned+=earned;run.pointsMax+=max;run.wrongAttempts+=st.wrongAttempts;const cat=run.scoreByCategory[category]||{earned:0,max:0};cat.earned+=earned;cat.max+=max;run.scoreByCategory[category]=cat;delete run.drafts?.[stageId];run.lastActionAt=st.completedAt;save();return st}
export function finishCaseV2(c){const h=caseV2Progress(c.id),run=h.activeRun;if(!run||run.finished)return{score:h.lastScore,earned:0,duplicate:true,categories:{}};run.finished=true;run.finishedAt=now();const score=run.pointsMax?Math.round(run.pointsEarned/run.pointsMax*100):0;const categories=Object.fromEntries(Object.entries(run.scoreByCategory).map(([k,v])=>[k,v.max?Math.round(v.earned/v.max*100):0]));run.finalScore=score;run.finalCategories=categories;h.completedRuns+=1;h.completed=true;h.lastScore=score;h.bestScore=Math.max(h.bestScore||0,score);h.lastCompletedAt=run.finishedAt;let earned=0;if(!h.xpAwarded){h.xpAwarded=true;earned=c.xp||20;state.xp+=earned;studyDay()}h.activeRun=null;save();return{score,earned,categories,wrongAttempts:run.wrongAttempts,notebook:run.notebook,run}}
export function caseApplicationSummary(caseItems,area){const list=(caseItems||[]).filter(c=>c.area===area&&['CURRENT','UPDATED'].includes(c.status));if(!list.length)return{score:0,completed:0,total:0};let totalScore=0,completed=0;for(const c of list){const h=caseV2Progress(c.id);if(h.completed){completed+=1;totalScore+=h.bestScore||0}}return{score:Math.round(totalScore/list.length),completed,total:list.length}}
const levels=[['Débutant',0],['Initié',250],['Entrepreneur',700],['Gestionnaire',1400],['Stratège',2400],['Expert',3800],['Corporate Master',5600]];
export function level(){let i=0;for(let x=0;x<levels.length;x++)if(state.xp>=levels[x][1])i=x;const cur=levels[i],next=levels[i+1]||[cur[0],cur[1]+800],range=next[1]-cur[1];return{name:cur[0],number:i+1,start:cur[1],next:next[1],pct:Math.min(100,Math.max(0,Math.round((state.xp-cur[1])/range*100))),inside:state.xp-cur[1],range}}
applyPrefs();