const KEY='lexifrance-state-v5';
const LEGACY_KEYS=['lexifrance-state-v4','lexifrance-state-v3','lexifrance-state-v2','lexifrance-state'];
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toISOString();
const days=(a,b=today())=>a?Math.floor((new Date(b)-new Date(a))/86400000):9999;
const base=()=>({xp:0,streak:0,lastStudyDay:null,completed:[],saved:[],lessonProgress:{},legacyMastery:{},caseHistory:{},name:'',theme:'light',font:16,currentPath:'Corporate',currentLesson:null,migratedCourseV5:false});
function safeParse(raw){try{return JSON.parse(raw||'null')}catch{return null}}
function load(){const current=safeParse(localStorage.getItem(KEY));if(current)return{...base(),...current};for(const k of LEGACY_KEYS){const s=safeParse(localStorage.getItem(k));if(s){const merged={...base(),...s};if(merged.name==='Petr')merged.name='';return merged}}return base()}
export const state=load();
export function save(){localStorage.setItem(KEY,JSON.stringify(state))}
export function applyPrefs(){document.body.classList.toggle('dark',state.theme==='dark');document.documentElement.style.setProperty('--body-size',`${state.font||16}px`)}
export function setTheme(v){state.theme=v;save();applyPrefs()}
export function setFont(delta){state.font=Math.max(16,Math.min(20,(state.font||16)+delta));save();applyPrefs()}
function emptyQuestion(){return{solved:false,attempts:0,wrongAttempts:0,firstAttemptCorrect:null,lastAnsweredAt:null,solvedAt:null}}
function emptyLesson(){return{opened:false,openedAt:null,mastery:0,questions:{},xpClaimed:false,lastAnsweredAt:null}}
function normalizeLesson(p={}){const out={...emptyLesson(),...p,questions:{...(p.questions||{})}};out.mastery=masteryFrom(out);return out}
function masteryFrom(p){const solved=Object.values(p.questions||{}).filter(q=>q?.solved).length;return Math.min(100,(p.opened?10:0)+(solved*9))}
export function lessonProgress(id){if(!state.lessonProgress[id])state.lessonProgress[id]=emptyLesson();const p=normalizeLesson(state.lessonProgress[id]);state.lessonProgress[id]=p;return p}
export function mastery(id){const p=lessonProgress(id);return{score:masteryFrom(p),opened:p.opened,solved:Object.values(p.questions||{}).filter(q=>q?.solved).length}}
export function masteryLabel(score){if(score>=100)return['Mastered','Освоено',5];if(score>=73)return['Applied','Применяете',4];if(score>=46)return['Practiced','Практикуете',3];if(score>=19)return['Understood','Изучаете',2];if(score>=10)return['Seen','Открыто',1];return['New','Не начато',0]}
export function migrateCourseV5(map={}){if(state.migratedCourseV5)return;const oldMastery=state.mastery||{};state.legacyMastery={...(state.legacyMastery||{}),...oldMastery};const oldCompleted=[...(state.completed||[])];const oldSaved=[...(state.saved||[])];const mappedCompleted=[...new Set(oldCompleted.map(id=>map[id]||id))];const mappedSaved=[...new Set(oldSaved.map(id=>map[id]||id))];const touched=new Set([...Object.keys(oldMastery).map(id=>map[id]||id),...mappedCompleted,...mappedSaved]);for(const id of touched){const p=lessonProgress(id);const legacyIds=Object.keys(oldMastery).filter(x=>(map[x]||x)===id);const legacyScore=Math.max(0,...legacyIds.map(x=>oldMastery[x]?.score||0));if(legacyScore>=10||mappedCompleted.includes(id)){p.opened=true;p.openedAt=p.openedAt||now()}if(mappedCompleted.includes(id))p.xpClaimed=true;p.mastery=masteryFrom(p);state.lessonProgress[id]=p}state.completed=mappedCompleted;state.saved=mappedSaved;if(state.currentLesson)state.currentLesson=map[state.currentLesson]||state.currentLesson;if(state.name==='Petr')state.name='';delete state.mastery;delete state.quizResults;state.migratedCourseV5=true;save()}
function studyDay(){const t=today();if(state.lastStudyDay===t)return;if(state.lastStudyDay&&days(state.lastStudyDay,t)===1)state.streak=(state.streak||0)+1;else state.streak=1;state.lastStudyDay=t}
export function openLessonProgress(id){const p=lessonProgress(id);const first=!p.opened;if(first){p.opened=true;p.openedAt=now();p.mastery=masteryFrom(p)}state.currentLesson=id;save();return{first,score:p.mastery}}
export function answerQuestion(lessonId,questionId,correct,lessonXp=0){const p=lessonProgress(lessonId);if(!p.opened){p.opened=true;p.openedAt=now()}const before=masteryFrom(p);const q={...emptyQuestion(),...(p.questions[questionId]||{})};q.attempts+=1;if(q.firstAttemptCorrect===null)q.firstAttemptCorrect=!!correct;if(!correct)q.wrongAttempts+=1;q.lastAnsweredAt=now();let newlySolved=false;if(correct&&!q.solved){q.solved=true;q.solvedAt=now();newlySolved=true;studyDay()}p.questions[questionId]=q;p.lastAnsweredAt=q.lastAnsweredAt;p.mastery=masteryFrom(p);let earned=0;let completedNow=false;if(p.mastery===100&&!p.xpClaimed){p.xpClaimed=true;earned=lessonXp||0;state.xp+=earned;completedNow=true;if(!state.completed.includes(lessonId))state.completed.push(lessonId)}else if(p.mastery===100&&!state.completed.includes(lessonId)){state.completed.push(lessonId)}save();return{correct,newlySolved,before,after:p.mastery,earned,completedNow,question:{...q}}}
export function questionProgress(lessonId,questionId){return{...emptyQuestion(),...(lessonProgress(lessonId).questions[questionId]||{})}}
export function pathMastery(ids){if(!ids?.length)return 0;return Math.round(ids.reduce((sum,id)=>sum+mastery(id).score,0)/ids.length)}
export function dueReviews(ids){return(ids||[]).filter(id=>{const p=lessonProgress(id);if(!p.opened||masteryFrom(p)>=100)return false;return p.lastAnsweredAt&&days(p.lastAnsweredAt.slice(0,10))>=7})}
export function toggleSaved(id){const i=state.saved.indexOf(id);if(i>=0)state.saved.splice(i,1);else state.saved.push(id);save();return i<0}
function emptyCaseHistory(){return{attempts:0,wrongAnswers:0,correctAnswers:0,firstAttemptCorrect:null,perfectRun:false,completed:false,completedAt:null,lastAttemptAt:null,xpAwarded:false,activeRun:null}}
export function caseProgress(id){if(!state.caseHistory[id])state.caseHistory[id]=emptyCaseHistory();else{const current=state.caseHistory[id],defaults=emptyCaseHistory();for(const[k,v]of Object.entries(defaults))if(current[k]===undefined)current[k]=v}return state.caseHistory[id]}
export function beginCaseRun(id){const h=caseProgress(id);if(h.activeRun&&!h.activeRun.finished)return h.activeRun;h.attempts+=1;h.lastAttemptAt=now();h.activeRun={id:`${id}-run-${h.attempts}`,startedAt:h.lastAttemptAt,wrongAnswers:0,correctAnswers:0,answers:{},finished:false};save();return h.activeRun}
export function restartCaseRun(id){const h=caseProgress(id);if(h.activeRun)h.activeRun.finished=true;h.attempts+=1;h.lastAttemptAt=now();h.activeRun={id:`${id}-run-${h.attempts}`,startedAt:h.lastAttemptAt,wrongAnswers:0,correctAnswers:0,answers:{},finished:false};save();return h.activeRun}
export function recordCaseAnswer(id,key,correct){const h=caseProgress(id),run=beginCaseRun(id);const k=String(key);const prior=run.answers[k]||{attempts:0,wrongAttempts:0,solved:false};prior.attempts+=1;if(correct){prior.solved=true;run.correctAnswers+=1;h.correctAnswers+=1}else{prior.wrongAttempts+=1;run.wrongAnswers+=1;h.wrongAnswers+=1}prior.lastAnsweredAt=now();run.answers[k]=prior;h.lastAttemptAt=prior.lastAnsweredAt;if(h.firstAttemptCorrect===null&&h.attempts===1&&Object.keys(run.answers).length===1)h.firstAttemptCorrect=!!correct;save();return{...prior,runWrong:run.wrongAnswers}}
export function finishCaseRun(c){const h=caseProgress(c.id),run=beginCaseRun(c.id);run.finished=true;run.finishedAt=now();const perfect=run.wrongAnswers===0;h.completed=true;h.completedAt=h.completedAt||run.finishedAt;h.perfectRun=h.perfectRun||perfect;h.lastAttemptAt=run.finishedAt;let earned=0;if(perfect&&!h.xpAwarded){h.xpAwarded=true;earned=c.xp||15;state.xp+=earned;studyDay()}h.activeRun=null;save();return{perfect,earned,attempts:h.attempts,wrongAnswers:h.wrongAnswers}}
export function caseAccuracy(id){const h=caseProgress(id),n=h.correctAnswers+h.wrongAnswers;return n?Math.round(h.correctAnswers/n*100):0}
const levels=[['Débutant',0],['Initié',250],['Entrepreneur',700],['Gestionnaire',1400],['Stratège',2400],['Expert',3800],['Corporate Master',5600]];
export function level(){let i=0;for(let x=0;x<levels.length;x++)if(state.xp>=levels[x][1])i=x;const cur=levels[i],next=levels[i+1]||[cur[0],cur[1]+800],range=next[1]-cur[1];return{name:cur[0],number:i+1,start:cur[1],next:next[1],pct:Math.min(100,Math.max(0,Math.round((state.xp-cur[1])/range*100))),inside:state.xp-cur[1],range}}
applyPrefs();