import{state,level,mastery,pathMastery}from'./state.js';import{icon,pathIcon}from'./icons.js';
export const section=(n,t,m='')=>`<div class="section-head"><div class="section-title"><div class="section-num">${n}</div><h2>${t}</h2></div>${m?`<div class="section-meta">${m}</div>`:''}</div>`;
export const statusBadge=s=>s==='CURRENT'?'<span class="status current">Проверено</span>':'<span class="status review">На проверке</span>';
export const errorBox=e=>`<div class="card legal-card"><h3>Не удалось загрузить</h3><p>${String(e?.message||e)}</p></div>`;
export const loading=t=>`<main style="padding:20px"><div class="card legal-card"><p>${t}</p></div></main>`;
export function levelCard(){const l=level();return `<div class="card level-card"><div><span class="level-badge">Уровень ${l.number}</span><h2>${l.name}</h2><p>${l.inside} из ${l.range} XP до следующего уровня</p></div><div class="ring" style="--p:${l.pct}"><div><b>${l.pct}%</b><span>LEVEL</span></div></div></div>`}
export function masteryBar(id){const m=mastery(id);return `<div class="progress"><i style="width:${m.score}%"></i></div><div class="micro" style="margin-top:4px">Mastery ${m.score}%</div>`}
export function pathCard(p){const pct=pathMastery(p.lessonIds);return `<div class="card path-card"><div class="tag">${pathIcon(p.id)} ${p.title}</div><h3>${pct}% освоено</h3><div class="progress"><i style="width:${pct}%"></i></div><div class="micro" style="margin-top:6px">${p.lessonIds.length} полноценных уроков</div></div>`}
export function shell(root,page,body){const nav=[['home','Главная','home'],['learn','Учиться','learn'],['solve','Решить','solve'],['search','Поиск','search'],['profile','Профиль','profile']];root.innerHTML=`<header class="top"><div class="brand"><div class="logo">L</div><strong>LexiFrance</strong></div><div class="top-actions"><div class="counter fire">🔥 ${state.streak||0}</div><div class="counter">⚡ ${state.xp||0}</div><button class="profile-dot hit" data-nav="profile">${(state.name||'P')[0].toUpperCase()}</button></div></header><main>${body}</main><nav class="nav"><div class="nav-inner">${nav.map(x=>`<button data-nav="${x[0]}" class="${page===x[0]?'active':''}">${icon(x[2])}<span>${x[1]}</span></button>`).join('')}</div></nav>`}
export function modalBase(kicker,meta,body,extra=''){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-head"><button class="back hit" data-close aria-label="Назад">‹</button><div><div class="tag">${kicker}</div><div class="micro">${meta}</div></div>${extra}</div><div class="modal-body">${body}</div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();return m}