import{state,level,mastery,masteryLabel}from'./state.js';import{icon,pathIcon}from'./icons.js';
export function header(){return `<header class="top"><div class="brand"><div class="logo">L</div><strong>LexiFrance</strong></div><div class="top-actions"><div class="counter fire" aria-label="Серия обучения">🔥 <b>${state.streak||0}</b></div><div class="counter" aria-label="XP">⚡ <b>${state.xp||0}</b></div><button class="profile-dot hit" data-nav="profile" aria-label="Профиль">${(state.name||'L')[0].toUpperCase()}</button></div></header>`}
const navs=[['home','Главная','home'],['learn','Учиться','learn'],['solve','Решить','solve'],['search','Поиск','search'],['profile','Профиль','profile']];
export function nav(page){return `<nav class="nav"><div class="nav-inner">${navs.map(n=>`<button class="${page===n[0]?'active':''}" data-nav="${n[0]}" aria-label="${n[1]}">${icon(n[2])}<span>${n[1]}</span></button>`).join('')}</div></nav>`}
export function shell(root,page,body){root.innerHTML=`${header()}<main>${body}</main>${nav(page)}`}
export function section(n,title,meta=''){return `<div class="section-head"><div class="section-title"><div class="section-num">${n}</div><h2>${title}</h2></div>${meta?`<div class="section-meta">${meta}</div>`:''}</div>`}
export function statusBadge(s){if(s==='CURRENT')return`<span class="status current">Проверено</span>`;if(s==='UPDATED')return`<span class="status current">Обновлено</span>`;return`<span class="status review">На проверке</span>`}
export function masteryBar(id){const m=mastery(id),lab=masteryLabel(m.score);return `<div class="mastery"><b>${lab[1]} ${m.score}%</b><div class="progress"><i style="width:${m.score}%"></i></div></div>`}
export function pathCard(p,pct,wide=false){return `<div class="card path-card ${wide?'wide':''}"><div class="path-top"><div class="path-icon">${pathIcon(p.id)}</div><b class="small">${pct}%</b></div><div><h3>${p.title}</h3><p>${p.description}</p><div class="progress" style="margin-top:9px"><i style="width:${pct}%"></i></div></div></div>`}
export function levelCard(){const l=level();return `<div class="level-card"><div><span class="badge">Уровень ${l.number}</span><h2>${l.name}</h2><p>${l.inside} из ${l.range} XP до следующего уровня</p></div><div class="ring" style="--p:${l.pct}"><div><strong>${l.pct}%</strong><span>LEVEL</span></div></div></div>`}
export function loading(text='Загрузка...'){return `<div class="card empty">${text}</div>`}
export function errorBox(e){return `<div class="notice"><strong>Не удалось загрузить раздел.</strong><br>${navigator.onLine?'Обновите страницу и попробуйте снова.':'Вы офлайн. Откройте материал один раз онлайн, чтобы сохранить его для офлайн-доступа.'}</div>`}
export function modalBase(title,sub,body,extra=''){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-head"><button class="back hit" data-close aria-label="Назад">${icon('back')}</button><div><b>${title}</b><div class="micro">${sub||''}</div></div>${extra}</div><div class="modal-body">${body}</div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();return m}
export function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
