(()=>{'use strict';
const T={plasma:{name:'Plasma Cannon',role:'Core DPS',cost:52,range:142,rate:'1.00/s',damage:26,accent:'#42d8ff',rgb:'66,216,255',pos:'0%',fx:'plasma'},frost:{name:'Frost Tower',role:'Control',cost:78,range:118,rate:'1.15/s',damage:0,accent:'#89f1ff',rgb:'137,241,255',pos:'25%',fx:'frost'},sniper:{name:'Sniper Rail',role:'Boss Killer',cost:132,range:245,rate:'0.54/s',damage:86,accent:'#cb91ff',rgb:'203,145,255',pos:'50%',fx:'sniper'},tesla:{name:'Electro Tower',role:'Energy Chain',cost:124,range:176,rate:'0.85/s',damage:22,accent:'#ffb443',rgb:'255,180,67',pos:'75%',fx:'tesla'},cannon:{name:'Cannon Tower',role:'Area Damage',cost:148,range:226,rate:'0.62/s',damage:58,accent:'#ff9835',rgb:'255,152,53',pos:'100%',fx:'cannon'}};const order=Object.keys(T),$=id=>document.getElementById(id),el={vp:$('viewport'),art:$('art'),blur:$('blur'),mini:$('mini'),dock:$('dock'),name:$('name'),role:$('role'),cost:$('cost'),range:$('range'),rate:$('rate'),damage:$('damage'),combat:$('combat'),idle:$('idle'),fx:$('fx'),loader:$('loader')};let cur='plasma',mode='combat',zoom=1,px=0,py=0,drag=null,last=performance.now(),timer=.25,parts=[],beams=[];const sprite='data:image/avif;base64,'+(window.BIOCORE_SPRITE_PARTS||[]).join('');document.documentElement.style.setProperty('--sprite',`url("${sprite}")`);const ctx=el.fx.getContext('2d');
function cards(){order.forEach(id=>{let t=T[id],b=document.createElement('button');b.className='card'+(id===cur?' on':'');b.dataset.id=id;b.style.setProperty('--ca',t.accent);b.innerHTML=`<div class="thumb" style="--cp:${t.pos}"></div><div class="ct"><b>${t.name}</b><span>${t.role}</span></div>`;b.onclick=()=>select(id,true);el.dock.appendChild(b)})}
function setPos(pos){document.documentElement.style.setProperty('--pos',pos);el.art.style.backgroundPosition=`${pos} center`;el.blur.style.backgroundPosition=`${pos} center`;el.mini.style.backgroundPosition=`${pos} center`}
function select(id,scroll){cur=id;let t=T[id];document.documentElement.style.setProperty('--accent',t.accent);document.documentElement.style.setProperty('--rgb',t.rgb);setPos(t.pos);el.name.textContent=t.name;el.role.textContent=t.role;el.cost.textContent=t.cost;el.range.textContent=t.range;el.rate.textContent=t.rate;el.damage.textContent=t.damage;zoom=1;px=py=0;apply();document.querySelectorAll('.card').forEach(c=>c.classList.toggle('on',c.dataset.id===id));if(scroll)document.querySelector(`.card[data-id="${id}"]`)?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});timer=.12;parts.length=0;beams.length=0}
function apply(){el.art.style.setProperty('--zoom',zoom);el.art.style.setProperty('--panx',px+'px');el.art.style.setProperty('--pany',py+'px')}
function setMode(m){mode=m;el.vp.classList.toggle('idle',m==='idle');el.combat.classList.toggle('on',m==='combat');el.idle.classList.toggle('on',m==='idle');parts.length=0;beams.length=0;timer=.12}el.combat.onclick=()=>setMode('combat');el.idle.onclick=()=>setMode('idle');
el.vp.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,px,py};el.vp.setPointerCapture?.(e.pointerId)});el.vp.addEventListener('pointermove',e=>{if(!drag)return;px=Math.max(-40,Math.min(40,drag.px+(e.clientX-drag.x)*.22));py=Math.max(-40,Math.min(40,drag.py+(e.clientY-drag.y)*.22));apply()});['pointerup','pointercancel'].forEach(n=>el.vp.addEventListener(n,()=>drag=null));el.vp.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(1,Math.min(1.16,zoom+(e.deltaY<0?.035:-.035)));apply()},{passive:false});
function resize(){let r=el.vp.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);el.fx.width=r.width*d;el.fx.height=r.height*d;el.fx.style.width=r.width+'px';el.fx.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);
const rnd=(a,b)=>a+Math.random()*(b-a);function spark(x,y,color,n=9,p=55){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=rnd(p*.35,p);parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.18,.48),max:.48,r:rnd(1,2.5),color})}}function beam(x1,y1,x2,y2,color,w=3,life=.13,j=false){beams.push({x1,y1,x2,y2,color,w,life,max:life,j,seed:Math.random()*20})}function fire(w,h){let f=T[cur].fx;if(f==='plasma'){beam(w*.48,h*.57,w*.80,h*.39,'#68e9ff',5,.16);spark(w*.80,h*.39,'#baf8ff',13,70);spark(w*.80,h*.39,'#ff9b35',5,40)}else if(f==='sniper'){beam(w*.45,h*.60,w*.82,h*.28,'#9ceaff',2.2,.11);spark(w*.82,h*.28,'#d8b4ff',10,78)}else if(f==='tesla'){beam(w*.44,h*.58,w*.78,h*.27,'#8ceeff',3,.18,true);beam(w*.78,h*.27,w*.83,h*.47,'#78ddff',2.4,.16,true);beam(w*.83,h*.47,w*.76,h*.66,'#78ddff',2.4,.16,true);spark(w*.78,h*.27,'#c4fbff',8,55);spark(w*.83,h*.47,'#c4fbff',8,55)}else if(f==='frost'){for(let i=0;i<24;i++)parts.push({x:w*.73+rnd(-32,32),y:h*.40+rnd(-25,25),vx:rnd(-28,28),vy:rnd(-36,18),life:rnd(.35,.8),max:.8,r:rnd(1,3),color:'#d9fbff'});beams.push({ring:true,x:w*.72,y:h*.41,r:8,life:.46,max:.46,color:'#b9f8ff'})}else{spark(w*.60,h*.46,'#ffab3b',18,90);beams.push({ring:true,x:w*.79,y:h*.37,r:6,life:.28,max:.28,color:'#ff9e32'})}}
function cadence(){return{plasma:.83,frost:1.18,sniper:1.75,tesla:1.04,cannon:1.35}[cur]}
function loop(now){requestAnimationFrame(loop);let dt=Math.min((now-last)/1000,.033);last=now;let w=el.vp.clientWidth,h=el.vp.clientHeight;ctx.clearRect(0,0,w,h);if(mode==='combat'){timer-=dt;if(timer<=0){fire(w,h);timer=cadence()}}for(let i=beams.length-1;i>=0;i--){let b=beams[i];b.life-=dt;if(b.life<=0){beams.splice(i,1);continue}let a=b.life/b.max;ctx.globalAlpha=a;ctx.strokeStyle=b.color;ctx.shadowColor=b.color;ctx.shadowBlur=12;if(b.ring){b.r+=dt*135;ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.stroke()}else{ctx.lineWidth=b.w;ctx.beginPath();ctx.moveTo(b.x1,b.y1);if(b.j){for(let q=1;q<9;q++){let k=q/9;ctx.lineTo(b.x1+(b.x2-b.x1)*k+Math.sin((q+b.seed)*6)*8,b.y1+(b.y2-b.y1)*k+Math.cos((q+b.seed)*5)*7)}}ctx.lineTo(b.x2,b.y2);ctx.stroke()}ctx.shadowBlur=0;ctx.globalAlpha=1}for(let i=parts.length-1;i>=0;i--){let p=parts[i];p.life-=dt;if(p.life<=0){parts.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;ctx.globalAlpha=Math.min(1,p.life/p.max*1.3);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.globalAlpha=1}}
cards();resize();select('plasma');let im=new Image();im.onload=()=>setTimeout(()=>{el.loader.style.opacity=0;setTimeout(()=>el.loader.remove(),320)},100);im.onerror=()=>{el.loader.style.opacity=0;setTimeout(()=>el.loader.remove(),320)};im.src=sprite;setTimeout(()=>{if(document.body.contains(el.loader)){el.loader.style.opacity=0;setTimeout(()=>el.loader.remove(),320)}},3000);requestAnimationFrame(loop);
})();