insert into public.legal_sources(id,jurisdiction,source_type,publisher,title,url,article,legal_area,effective_from,effective_until,last_verified_at,status,content_hash,official,published,metadata) values
('src-corp-statuts','FR','guidance','DILA','Création d’une société : rédaction et enregistrement des statuts','https://entreprendre.service-public.fr/vosdroits/F32232',null,'Corporate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-corp-statuts-20260822',true,true,'{"lessonIds":["corp-01","corp-03"]}'),
('src-corp-capital','FR','guidance','DILA','Constitution et dépôt du capital social','https://entreprendre.service-public.fr/vosdroits/F32333',null,'Corporate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-corp-capital-20260822',true,true,'{"lessonIds":["corp-02"]}'),
('src-corp-transfer','FR','guidance','DILA','Transmission d’entreprise : cession de parts sociales à un tiers','https://entreprendre.service-public.fr/vosdroits/F36016',null,'Corporate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-corp-transfer-20260822',true,true,'{"lessonIds":["corp-04"]}'),
('src-corp-cessation','FR','guidance','DILA','Déclaration de cessation des paiements','https://entreprendre.service-public.fr/vosdroits/F22352',null,'Corporate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-corp-cessation-20260822',true,true,'{"lessonIds":["corp-05"]}'),
('src-tax-tva','FR','guidance','DGFiP','TVA - espace professionnel','https://www.impots.gouv.fr/professionnel/tva','Article 293 B CGI','Tax','2026-01-01',null,'2026-08-22T00:00:00Z','CURRENT','p4-tax-tva-20260822',true,true,'{"lessonIds":["tax-02"]}'),
('src-tax-bofip-franchise','FR','doctrine','DGFiP','BOI-TVA-DECLA-40-10 - Franchise en base de droit commun','https://bofip.impots.gouv.fr/bofip/855-PGP.html/identifiant%3DBOI-TVA-DECLA-40-10-20260701','BOI-TVA-DECLA-40-10','Tax','2026-07-01',null,'2026-08-22T00:00:00Z','CURRENT','p4-tax-bofip-franchise-20260701',true,true,'{"lessonIds":["tax-02"]}'),
('src-tax-bofip-consequences','FR','doctrine','DGFiP','BOI-TVA-DECLA-40-10-20 - Conséquences de la franchise','https://bofip.impots.gouv.fr/bofip/1079-PGP.html/identifiant%3DBOI-TVA-DECLA-40-10-20-20260701','BOI-TVA-DECLA-40-10-20','Tax','2026-07-01',null,'2026-08-22T00:00:00Z','CURRENT','p4-tax-bofip-consequences-20260701',true,true,'{"lessonIds":["tax-02"]}'),
('src-imm-r911-1','FR','legislation','Légifrance','CESEDA - Article R911-1','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000054213317','R911-1','Immigration','2026-06-08',null,'2026-08-22T00:00:00Z','CURRENT','p4-imm-r911-1-20260608',true,true,'{"lessonIds":["imm-06"]}'),
('src-imm-r921','FR','legislation','Légifrance','CESEDA - Délais accélérés Articles R921-1 à R921-3','https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006070158/LEGISCTA000049975190/','R921-1 à R921-3','Immigration','2026-06-08',null,'2026-08-22T00:00:00Z','CURRENT','p4-imm-r921-20260608',true,true,'{"lessonIds":["imm-06"]}'),
('src-re-l271-1','FR','legislation','Légifrance','Code de la construction et de l’habitation - Article L271-1','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037667917','L271-1','Real Estate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-re-l271-1-20260822',true,true,'{"lessonIds":["re-01"]}'),
('src-re-deposit','FR','guidance','DILA','Dépôt de garantie dans un bail d’habitation','https://www.service-public.fr/particuliers/vosdroits/F31269','Loi n°89-462 du 6 juillet 1989','Real Estate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-re-deposit-20260822',true,true,'{"lessonIds":["re-02"]}'),
('src-re-urbanisme','FR','guidance','DILA','Autorisations d’urbanisme','https://www.service-public.fr/particuliers/vosdroits/N319',null,'Real Estate',null,null,'2026-08-22T00:00:00Z','CURRENT','p4-re-urbanisme-20260822',true,true,'{"lessonIds":["re-04"]}')
on conflict (id) do update set title=excluded.title,url=excluded.url,article=excluded.article,legal_area=excluded.legal_area,effective_from=excluded.effective_from,effective_until=excluded.effective_until,last_verified_at=excluded.last_verified_at,status=excluded.status,content_hash=excluded.content_hash,official=excluded.official,published=excluded.published,metadata=excluded.metadata,updated_at=now();

insert into public.legal_source_chunks(id,source_id,section,content,effective_from,effective_until,tags,jurisdiction,legal_area,status,content_hash,verified_at,metadata) values
('chunk-corp-statuts-01','src-corp-statuts','Rôle des statuts','Les statuts fixent les règles juridiques essentielles de fonctionnement de la société. Ils doivent être cohérents avec la forme sociale choisie, l’organisation des pouvoirs et les décisions que la société devra prendre.',null,null,array['statuts','gouvernance','société','SAS','SARL'],'FR','Corporate','CURRENT',md5('corp-statuts-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-corp-capital-01','src-corp-capital','Capital social','Le capital social correspond aux apports affectés au capital et figure dans les statuts. Il ne doit pas être confondu avec le solde bancaire disponible de la société après son immatriculation.',null,null,array['capital social','apport','fonds propres'],'FR','Corporate','CURRENT',md5('corp-capital-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-corp-capital-02','src-corp-capital','Apport et droits sociaux','Un apport au capital participe à la structure des droits sociaux. Une somme mise à disposition de la société sans augmentation de capital ne doit pas être qualifiée automatiquement comme apport au capital.',null,null,array['apport','actions','parts sociales'],'FR','Corporate','CURRENT',md5('corp-capital-02'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-corp-transfer-01','src-corp-transfer','Cession de parts','La cession de parts sociales transfère des droits dans le capital et peut être soumise à des étapes ou restrictions propres à la forme sociale et aux clauses applicables. Les statuts et, lorsqu’il existe, le pacte doivent être vérifiés avant la transaction.',null,null,array['cession','agrément','préemption','parts sociales'],'FR','Corporate','CURRENT',md5('corp-transfer-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-corp-cessation-01','src-corp-cessation','Cessation des paiements','La cessation des paiements repose sur l’impossibilité de faire face au passif exigible avec l’actif disponible. Une analyse sérieuse distingue donc les dettes immédiatement exigibles des actifs réellement disponibles.',null,null,array['cessation des paiements','passif exigible','actif disponible','insolvabilité'],'FR','Corporate','CURRENT',md5('corp-cessation-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-corp-cessation-02','src-corp-cessation','Compte courant et actif disponible','Des avances en compte courant non bloquées et non réclamées peuvent entrer dans l’analyse de l’actif disponible selon leur situation. La qualification dépend des conditions réelles de disponibilité et d’exigibilité.',null,null,array['compte courant','CCA','actif disponible'],'FR','Corporate','CURRENT',md5('corp-cessation-02'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-tax-tva-01','src-tax-tva','Franchise en base 2026','Pour 2026, la franchise en base de TVA de droit commun distingue notamment les activités de vente/hébergement et les prestations de services. La qualification de l’activité et le chiffre d’affaires de référence doivent être déterminés avant d’appliquer un seuil.','2026-01-01',null,array['TVA','franchise en base','chiffre d’affaires','seuil'],'FR','Tax','CURRENT',md5('tax-tva-01-2026'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-tax-tva-02','src-tax-tva','Seuils de droit commun 2026','En 2026, la page professionnelle de la DGFiP indique 85 000 € pour certaines activités de vente/hébergement et 37 500 € pour les prestations de services, avec des seuils majorés respectifs de 93 500 € et 41 250 € pour la perte en cours d’année selon les conditions applicables.','2026-01-01',null,array['TVA','85000','37500','93500','41250'],'FR','Tax','CURRENT',md5('tax-tva-02-2026'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-tax-bofip-01','src-tax-bofip-franchise','Nature de la franchise','La franchise en base est un régime de simplification pour les petits assujettis qui remplissent les conditions prévues. L’assujetti qui en bénéficie peut renoncer au régime en optant pour le paiement de la TVA.','2026-07-01',null,array['TVA','franchise','option'],'FR','Tax','CURRENT',md5('tax-bofip-01-20260701'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-tax-bofip-02','src-tax-bofip-consequences','Conséquences de la franchise','Un bénéficiaire de la franchise en base est dispensé du paiement de la TVA mais ne peut pas déduire la TVA grevant les biens et services acquis pour les besoins de son activité, sous réserve des règles applicables.','2026-07-01',null,array['TVA','déduction','franchise'],'FR','Tax','CURRENT',md5('tax-bofip-02-20260701'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-imm-r911-01','src-imm-r911-1','Délai général de recours','Depuis le 8 juin 2026, lorsque le CESEDA renvoie à l’article R911-1, le tribunal administratif peut être saisi dans le délai d’un mois à compter de la notification de la décision. L’exercice d’un recours administratif ne proroge pas ce délai contentieux.','2026-06-08',null,array['OQTF','recours','délai','un mois','tribunal administratif'],'FR','Immigration','CURRENT',md5('imm-r911-01-20260608'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-imm-r921-01','src-imm-r921','Assignation à résidence','Lorsqu’une assignation à résidence intervient avant l’expiration du délai applicable, l’administration doit informer l’intéressé de l’interruption du délai en cours et du nouveau délai accéléré applicable. Depuis le 8 juin 2026, l’article R921-1 renvoie notamment au délai de sept jours prévu par le CESEDA.','2026-06-08',null,array['OQTF','assignation à résidence','sept jours','recours'],'FR','Immigration','CURRENT',md5('imm-r921-01-20260608'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-imm-r921-02','src-imm-r921','Rétention administrative','Le placement en rétention avant l’expiration d’un délai contentieux peut interrompre ce délai et déclencher le délai accéléré spécialement applicable à la rétention. Toute analyse doit identifier précisément la date, le mode de notification et la mesure de contrainte.','2026-06-08',null,array['OQTF','rétention','48 heures','notification','recours'],'FR','Immigration','CURRENT',md5('imm-r921-02-20260608'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-imm-r921-03','src-imm-r921','Facteurs procéduraux critiques','Pour calculer un délai OQTF, il faut au minimum qualifier le type de décision, connaître la date et le mode de notification, vérifier l’existence d’une assignation, d’une rétention ou d’une détention et identifier le régime procédural applicable à cette décision.','2026-06-08',null,array['OQTF','missing facts','notification','assignation','rétention'],'FR','Immigration','CURRENT',md5('imm-r921-03-20260608'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-re-l271-01','src-re-l271-1','Rétractation acquéreur non professionnel','L’acquéreur non professionnel d’un immeuble à usage d’habitation bénéficie d’un délai de rétractation de dix jours dans les conditions prévues par l’article L271-1. Le point de départ dépend de la première présentation ou de la remise répondant aux conditions légales.',null,null,array['immobilier','rétractation','10 jours','L271-1','acquéreur'],'FR','Real Estate','CURRENT',md5('re-l271-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-re-l271-02','src-re-l271-1','Calcul du point de départ','Le délai de dix jours commence le lendemain de la première présentation de la notification ou, selon les modalités légales, de la remise de l’acte. Le calcul ne doit donc pas partir automatiquement du jour de la signature.',null,null,array['immobilier','délai','notification','signature'],'FR','Real Estate','CURRENT',md5('re-l271-02'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-re-deposit-01','src-re-deposit','Objet du dépôt de garantie','Le dépôt de garantie couvre certains manquements du locataire, tels que loyers ou charges impayés et réparations locatives justifiées. Il ne remplace pas automatiquement le dernier loyer.',null,null,array['bail','dépôt de garantie','loyer','retenue'],'FR','Real Estate','CURRENT',md5('re-deposit-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-re-deposit-02','src-re-deposit','Restitution et preuve','Lorsque des retenues sont effectuées sur le dépôt de garantie, elles doivent être justifiées par des éléments pertinents tels que états des lieux, photographies, factures, devis ou autres preuves adaptées. Le délai de restitution dépend notamment de la conformité de l’état des lieux de sortie.',null,null,array['bail','dépôt de garantie','preuve','état des lieux'],'FR','Real Estate','CURRENT',md5('re-deposit-02'),'2026-08-22T00:00:00Z','{"claimLevel":true}'),
('chunk-re-deposit-03','src-re-deposit','Délais de restitution','Pour un bail d’habitation, Service-Public indique en principe un délai maximal d’un mois lorsque l’état des lieux de sortie est conforme à l’état des lieux d’entrée et de deux mois lorsqu’il ne l’est pas, à compter de la restitution des clés selon les modalités prévues.',null,null,array['bail','1 mois','2 mois','restitution','clés'],'FR','Real Estate','CURRENT',md5('re-deposit-03'),'2026-08-22T00:00:00Z','{"claimLevel":true,"volatile":true}'),
('chunk-re-urbanisme-01','src-re-urbanisme','Travaux et autorisations','Avant des travaux modifiant un bien, il faut identifier si une autorisation d’urbanisme est requise selon la nature du projet et les règles locales. L’absence de vérification peut entraîner un risque administratif et contentieux.',null,null,array['urbanisme','travaux','autorisation','permis'],'FR','Real Estate','CURRENT',md5('re-urbanisme-01'),'2026-08-22T00:00:00Z','{"claimLevel":true}')
on conflict (id) do update set source_id=excluded.source_id,section=excluded.section,content=excluded.content,effective_from=excluded.effective_from,effective_until=excluded.effective_until,tags=excluded.tags,jurisdiction=excluded.jurisdiction,legal_area=excluded.legal_area,status=excluded.status,content_hash=excluded.content_hash,verified_at=excluded.verified_at,metadata=excluded.metadata,updated_at=now();
